### ISSUE TITLE
CS.jl disconnecting pairs while CS 4.05 is not

### ISSUE THREAD

**Issue by rmarrotte** [Circuitscape/Circuitscape.jl#122]
Hi,
It seems like CS.jl is setting some pairs to -1, while CS 4.05 is still computing these pairs. I have a total of 268,278 pairs. CS.jl seems to think that 64,270 of these pairs are disconnected. Any ideas as to why CS.jl is doing this?
Thanks
Robby

![cs_and julia_output](https://user-images.githubusercontent.com/3258127/39528056-135e9e12-4df1-11e8-82c8-5825c0f16c0f.png)

**Comment by ranjanan** [comment]
Hi @rmarrotte, could you please paste the output of the following code on the Julia terminal: 
```julia
Pkg.status("Circuitscape")
```

Also, is there a way you could share your input so I can check? Thank you.

**Comment by rmarrotte** [comment]
Pkg.status("Circuitscape")
Circuitscape 5.0.0+ master
https://www.dropbox.com/sh/holv4uojhsfvvlr/AADpo4ZuKulk72iKtZJpz7Xwa?dl=0

**Comment by ranjanan** [comment]
Thanks,  @rmarrotte. According to logs, it seems to take a fewer pairs (86736) instead of the right number of pairs(268278). This seems to happen even as I disable the `include_pairs` option. Odd. I'll figure it out and let you know ASAP.

**Comment by rmarrotte** [comment]
Yes, @ranjanan I was wondering whether there was a maximum number of nodes or some kind of maximum resistance threshold or something. Also, I was thinking it could be that some nodes are very close to each other, but there isn't this pattern in the data at all.

**Comment by ranjanan** [comment]
No, I don't have either of those thresholds. I think I just made a mistake counting the number of pairs to solve. I'm investigating it right now.

**Comment by ranjanan** [comment]
@rmarrotte could you run the following commands at the Julia prompt: 
```julia
Pkg.checkout("Circuitscape")
Pkg.checkout("Circuitscape", "pt_calc")
```
restart Julia and then see if you're getting the right answer?  Just a hunch.

**Comment by rmarrotte** [comment]
@ranjanan No update was available, same results.

**Comment by rmarrotte** [comment]
@ranjanan It checked it out and found nothing new for both. Restarted Julia before I did this. Ran CS just in case, but nothing new.

**Comment by rmarrotte** [comment]
```
myfunction <- function(b,d){
   a <- b
   c <- d
```

**Comment by ranjanan** [comment]
Hi @rmarrotte I pushed one more commit to the same branch. Could you do `Pkg.checkout("Circuitscape", "pt_calc")` again and check please? Thanks.

**Comment by rmarrotte** [comment]
Nope, nothing new to update or install

**Comment by ranjanan** [comment]
Okay then. I'm sorry about this. I will run this privately and come up with a fix.

**Comment by ranjanan** [comment]
Hi Robby, I'm really sorry, but I'm having some trouble because your example has a really high number of pairs to solve which makes it hard to debug this. Is there a slightly smaller problem that you have where you can reproduce this behaviour?

**Comment by ranjanan** [comment]
@rmarrotte ^

**Comment by ViralBShah** [comment]
@ranjanan Can we run connected components on the input and see if we are doing that correctly?

**Comment by rmarrotte** [comment]
@ranjanan Not really. Do you think it crashed because of 1 specific pair? Like I indicated a while back, there are some pairs that are right on top of each other within the same pixel. I think CS has some way of dealing with this by setting the effective resistance to 0 or -700.

**Comment by ranjanan** [comment]
@rmarrotte #167 also fixes this. Is there a smaller test you can run to confirm this?
