### ISSUE TITLE
Advanced run not completing in Julia

### ISSUE THREAD

**Issue by mgray505** [Circuitscape/Circuitscape.jl#131]
Hi Ranjan,
I mentioned to you today that we ran a configuration in the CS v.4.0 gui that finished in about 30 min, but when I've tried running it in Julia it's run for many hours without completing. I'm running it in 'advanced' mode where a pixel-wide strip of pixels (270m) runs across the northern part of the landscape and are assigned sources of unit current, and a pixel-wide strip in the southern edge of the landscape are connected directly to ground. The data also represents conductance instead of resistance. Here is a link to the conductance surface (bbmm_prediction_270_penalized_pow2_mult40.asc), source and ground asc, and the configuration file: https://drive.google.com/drive/u/2/folders/19C8T5EC-tWBEqSSo7Ppf6-BjaMo75Hc2

-Miranda

**Comment by ranjanan** [comment]
@mgray505 thank you for posting this issue!

Could you please paste the output of the following command at the Julia prompt: 
```
Pkg.status("Circuitscape")
```

**Comment by mgray505** [comment]
- Circuitscape 5.2.0+ master

**Comment by ranjanan** [comment]
Great, and would you happen to know what the size of the graph is? It should be part of the circuitscape logs.

**Comment by mgray505** [comment]
Graph has 5407745 nodes and 3 components.
Job took 36 minutes 27 seconds to complete.

**Comment by mgray505** [comment]
Hi @ranjanan  -
I did this and am now getting this error
<img width="669" alt="screen shot 2018-07-18 at 7 54 37 am" src="https://user-images.githubusercontent.com/12432192/42889705-ebf7e53a-8a5f-11e8-833d-3650062d1d3f.png">

**Comment by ranjanan** [comment]
@mgray505 that's very strange, given that the tests pass on #135. Could you post the output of 
`Pkg.status("Circuitscape")` please?

**Comment by mgray505** [comment]
<img width="522" alt="screen shot 2018-07-18 at 9 13 26 am" src="https://user-images.githubusercontent.com/12432192/42894114-e9df02aa-8a6a-11e8-9a31-2101d59cfe4d.png">

**Comment by mgray505** [comment]
<img width="571" alt="screen shot 2018-07-18 at 9 28 58 am" src="https://user-images.githubusercontent.com/12432192/42894919-10132f3a-8a6d-11e8-8c0a-b1da408a89ee.png">

**Comment by ranjanan** [comment]
Sorry if you're already done this, but could you restart Julia, do `using Circuitscape` and then do `Pkg.test("Circuitscape")` please?

**Comment by ranjanan** [comment]
Had a call with @mgray505 and fixed this. Turned out it was the same issue as #133 and then we had to update the Memento package
