### ISSUE TITLE
Advanced run hangs in Win10 Pro

### ISSUE THREAD

**Issue by jplatt-B54** [Circuitscape/Circuitscape.jl#133]
I’m having problems with my first attempts to run Circuitscape from the Julia prompt.

I’m using an .ini file (attached) that was generated when I ran Circuitscape using the ArcGIS tool.  It seems to start OK, but no other output is produced, even after running several hours.  The process memory and CPU usage is holding steady at 1.8GB and ~7% whenever I check it.

I’m running it in a Windows 10 Pro OS environment.

[errorTestData.zip](https://github.com/Circuitscape/Circuitscape.jl/files/2190191/errorTestData.zip)

**Comment by ranjanan** [comment]
@jplatt-B54 could you please try #135 and see if it works for you? You can access it by doing: `Pkg.checkout("Circuitscape", "adv")` and then restarting Julia and running it again.

**Comment by jplatt-B54** [comment]
It now works, you can close this issue.  Thanks!
