### ISSUE TITLE
Run silently

### ISSUE THREAD

**Issue by wpeterman** [Circuitscape/Circuitscape.jl#140]
Is it possible to run the program silently. That is, not to print the status of the run to the console?

**Comment by ranjanan** [comment]
Will expose this.

**Comment by ViralBShah** [comment]
Maybe have an ini file option as well.

**Comment by ranjanan** [comment]
Whoops, I think I've already implemented this. Can you try changing `log_level = critical` in your INI file? This is completely silent though with no logging whatsoever
