### ISSUE TITLE
Julia v. 0.6.4: ArgumentError: Unknown time zone "America/New York"

### ISSUE THREAD

**Issue by jbauder** [Circuitscape/Circuitscape.jl#145]
Hello,

I have installed Julia v. 0.6.4 on a computer with Windows 7 in order to run a version of the program CIRCUITSCAPE with Julia via R. I have installed Julia as well as the Windows updates and service packages needed to run on Windows 7 and loaded Circuitscape through Julia with the command Pkg.add("Circuitscape") following the instructions on Circuitscape's GitHub page. However, when I run Pkg.test("Circuitscape") I get an error saying: 
"ERROR: LoadError: LoadError: InitError: ArgumentError: Unknown time zone "America/New York"
I also get this error when I try to run Circuitscape with Julia via R using the R package 

I have not seen this error on other Windows 7 machines on which I have installed and run Julia and Circuitscape via R using JuliaCall which makes me think it is something unique with this particular computer. I tried installing the Julia package TimeZones but that has not solved the problem. I checked the date time setting on my computer and the time zone is listed as UTC-05:00 Eastern Time (US & Canada).
Does anyone have any ideas of why I might be getting this error?

Thank you very much for any help you can provide,
Javan

**Comment by simonbyrne** [comment]
link to discourse: https://discourse.julialang.org/t/julia-error-unknown-time-zone-america-new-york/14260

**Comment by ranjanan** [comment]
@jbauder could you please check if this occurs on Julia 1.0? Thank you
