### ISSUE TITLE
CodecZlib had build errors.

### ISSUE THREAD

**Issue by trecakov** [Circuitscape/Circuitscape.jl#147]
julia> Pkg.test("Circuitscape")
INFO: Testing Circuitscape
ERROR: LoadError: CodecZlib.jl is not installed properly, run Pkg.build("CodecZlib") and restart Julia.
Stacktrace:
 [1] error(::String) at ./error.jl:21
 [2] include_from_node1(::String) at ./loading.jl:576
 [3] include(::String) at ./sysimg.jl:14
 [4] anonymous at ./<missing>:2
while loading /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/pkg/v0.6/CodecZlib/src/CodecZlib.jl, in expression starting on line 42
ERROR: LoadError: Failed to precompile CodecZlib to /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/cache/CodecZlib.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:463
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] include(::String) at ./sysimg.jl:14
 [6] anonymous at ./<missing>:2
while loading /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/pkg/v0.6/LightGraphs/src/LightGraphs.jl, in expression starting on line 4
ERROR: LoadError: LoadError: LoadError: Failed to precompile LightGraphs to /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/cache/LightGraphs.ji.
Stacktrace:
 [1] compilecache(::String) at ./loading.jl:710
 [2] _require(::Symbol) at ./loading.jl:497
 [3] require(::Symbol) at ./loading.jl:405
 [4] include_from_node1(::String) at ./loading.jl:576
 [5] eval(::Module, ::Any) at ./boot.jl:235
 [6] _require(::Symbol) at ./loading.jl:490
 [7] require(::Symbol) at ./loading.jl:405
 [8] include_from_node1(::String) at ./loading.jl:576
while loading /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/pkg/v0.6/SimpleWeightedGraphs/src/SimpleWeightedGraphs.jl, in expression starting on line 3
while loading /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/pkg/v0.6/Circuitscape/src/Circuitscape.jl, in expression starting on line 3
while loading /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/pkg/v0.6/Circuitscape/test/runtests.jl, in expression starting on line 1
============================[ ERROR: Circuitscape ]=============================

failed process: Process(`/software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/bin/julia -Cnative -J/software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/lib/julia/sys.so --compile=yes --depwarn=yes --check-bounds=yes --code-coverage=none --color=yes --compilecache=yes /software/spack/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/julia-0.6.2-uwymgoyn5twl2vsoalaxdkwxxh6ujdy3/var/julia/pkg/v0.6/Circuitscape/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
ERROR: Circuitscape had test errors

I have searched for the solution, however, there are none for linux. 
Any suggestions are appreciated. 

Thanks

**Comment by ranjanan** [comment]
@trecakov could you tell me if running `Pkg.build("CodecZlib")` fails, and if so, paste the error message here?

**Comment by trecakov** [comment]
@ranjanan CodezZlib, failed... It couldnt download the file from the url, so I downloaded it manually and installed it. It fixes the problem. You can close this.

**Comment by ViralBShah** [comment]
If you could share the exact error message, we can try to get it fixed upstream.

**Comment by trecakov** [comment]
It was something like this:

INFO: Building CodecZlib
Info: Downloading https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.0/Zlib.x86_64-linux-gnu.tar.gz to /raid/home/thibaut/.julia/v0.6/CodecZlib/deps/usr/downloads/Zlib.x86_64-linux-gnu.tar.gz...
[16:28:38] curl: (48) An unknown option was passed in to libcurl
==========================================================================[ ERROR: CodecZlib ]==========================================================================

LoadError: Could not download https://github.com/bicycle1885/ZlibBuilder/releases/download/v1.0.0/Zlib.x86_64-linux-gnu.tar.gz to /raid/home/thibaut/.julia/v0.6/CodecZlib/deps/usr/downloads/Zlib.x86_64-linux-gnu.tar.gz
while loading /raid/home/thibaut/.julia/v0.6/CodecZlib/deps/build.jl, in expression starting on line 92

========================================================================================================================================================================

============================================================================[ BUILD ERRORS ]============================================================================

WARNING: CodecZlib had build errors.

 - packages with build errors remain installed in /raid/home/thibaut/.julia/v0.6
 - build the package(s) and all dependencies with `Pkg.build("CodecZlib")`
 - build a single package by running its `deps/build.jl` script

========================================================================================================================================================================

**Comment by ViralBShah** [comment]
We probably should try and move to Julia 1.0 as soon as possible.

**Comment by ranjanan** [comment]
We've moved to 1.0

**Comment by vlandau** [comment]
I had a similar issue with a Docker-built image using Ubuntu 16.04 as a base image
I had to run:
apt-get install -y lib1g-dev

Then, oddly enough, CS worked....
