### ISSUE TITLE
LoadError: UndefVarError: SparseMatrixCSC not defined

### ISSUE THREAD

**Issue by rhettdharrison** [Circuitscape/Circuitscape.jl#149]
I have just installed Julia and then Circuitscape, but I stumbled at the last hurdle. This is the what I get when trying to run Julia> using Circuitscape.

**Comment by rhettdharrison** [comment]
Ahh.. Yes I was using Julia v1.0. I will try again.

**Comment by ranjanan** [comment]
@rhettdharrison you can now use Circuitscape on Julia v1.0 on master.

**Comment by vlandau** [comment]
Does using Circuitscape in Julia v1.0.1 (or v0.7.0 for that matter) require installing the Circuitscape package differently? I get the error shown in the attached photo when trying to install on Julia v1.0.1, and Pkg.test("Circuitscape") fails in Julia v0.7.0. I'm using the 64-bit versions of Julia on Windows 10 pro. Alternatively, it does work on Julia v0.6.4

![juliaerror](https://user-images.githubusercontent.com/17304432/47881515-f1e26800-ddeb-11e8-9053-13a6b1ed4235.PNG)
