### ISSUE TITLE
Julia version compatibility with Circuitscape package?

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Circuitscape.jl#160]
@ranjanan Does using Circuitscape in Julia v1.0.1 (or v0.7.0 for that matter) require installing the Circuitscape package differently? I see in the comment on the thread linked below that Circuitscape is ported to Julia v1.0, but I get the error shown in the attached photo when trying to install on Julia v1.0.1, and Pkg.test("Circuitscape") fails in Julia v0.7.0. I'm using the 64-bit versions of Julia on Windows 10 pro. Alternatively, everything does work on Julia v0.6.4, so I'm sticking with it for now.

![juliaerror](https://user-images.githubusercontent.com/17304432/47881515-f1e26800-ddeb-11e8-9053-13a6b1ed4235.PNG)

_Originally posted by @vlandau in https://github.com/Circuitscape/Circuitscape.jl/issues/149#issuecomment-435196325_

**Comment by richardurs** [comment]
Me too in Julia 1.0

**Comment by blindjesse** [comment]
Installing the development version appears to work.

`Pkg.add(PackageSpec(name="Circuitscape", rev="master")`

or type `]` to go to the `pkg>` prompt and then do `add Circuitscape#master`
