### ISSUE TITLE
Warn() deprecated

### ISSUE THREAD

**Issue by rachelluethi** [Circuitscape/Circuitscape.jl#171]
When running simulations with Circuitscape 5.4.0 with Julia 1.0.1 it didn't recognize `warn()` in io.jl. I found out that from Julia v0.7.0 (https://docs.julialang.org/en/v0.7.0/NEWS/) `warn()` is deprecated and should be replaced by `@warn()`. By replacing `warn()` with `@warn()` in Lines 152-162 (at the current version: L176-186) the simulations run properly.

**Comment by ViralBShah** [comment]
@rachelluethi would you be comfortable with making a pull request to fix this?

**Comment by ViralBShah** [comment]
@ranjanan Close?

**Comment by ranjanan** [comment]
Fixed via e3c398897ea86303ee02a992602dde590bda1509
