### ISSUE TITLE
how to cite circuitscape.jl?

### ISSUE THREAD

**Issue by elkoen** [Circuitscape/Circuitscape.jl#173]
Hi,
I was wondering how to cite circuitscape.jl?
Thanks!
Erin

**Comment by ViralBShah** [comment]
@ranjanan Did we ever submit a JOSS article to cite circuitscape.jl?

**Comment by ranjanan** [comment]
No we didn't.

**Comment by ViralBShah** [comment]
@elkoen What is your timeline? We would love to have something for you to cite. We plan to write a paper and put it up in the next couple of weeks - but if your timeline is shorter, we'll put up a short JOSS publication.

**Comment by elkoen** [comment]
Thank-you for your quick reply. I am getting ready to submit a paper soon, but I can cite your github page as a placeholder for now.
Thanks!!

**Comment by ViralBShah** [comment]
Can you use:

"Circuitscape.jl: High performance circuit-theory computations in landscape ecology with Julia", Ranjan Anantharaman and Viral B. Shah, (In preparation).

**Comment by elkoen** [comment]
yes, that will work. Thanks!

**Comment by elkoen** [comment]
Hi again,
Just wondering if you have any updates for how to cite circuitscape.jl?
Thanks!
Erin

**Comment by ViralBShah** [comment]
@ranjanan Do we have a paper draft to put up somewhere? Is arxiv an option?

**Comment by ranjanan** [comment]
A preprint will be up very soon.

**Comment by elkoen** [comment]
I am sorry to keep bothering you about this. I am going to submit revisions to my paper in the next few weeks. Do you have any updates on how to cite circuitscape.jl?
Thanks!
Erin

**Comment by ranjanan** [comment]
@elkoen I'll put it up this week, for sure, and post the link here.

**Comment by ranjanan** [comment]
@elkoen I've submitted a preprint to ArXiV! Once its processed, I'll post a note about how one may cite it.

**Comment by ranjanan** [comment]
@elkoen the ArXiV article is now up! You can cite that: https://arxiv.org/abs/1906.03542
