### ISSUE TITLE
Potential speedups

### ISSUE THREAD

**Issue by glaroc** [Circuitscape/Circuitscape.jl#174]
Hi, I did some profiling on my Circuitscape runs and identified a couple of bottlenecks. 

On Julia 1.0.x, it seems like there is an issue with the readdlm() function. It is MUCH faster on 1.1.0 for opening large .asc files. So, just switching Julia versions decreased the run times by over 30%. 

I uncommented this line in out.jl (176) and commented out the loop that followed that was taking a while to run. 
`# s = vec(sum(branch_currents, 1))`

And replaced it with
   `s = vec(sum(branch_currents, dims=1))`

That also ran much faster. 

Thanks for the great work on this! The Julia version is awesome. The only issue for us now is the high RAM consumption which makes it nearly impossible to use on multi-core HPCs. A single run consumes about 150GB of RAM, so running multiple runs in parallel is not really possible.

**Comment by ViralBShah** [comment]
Why is it using 150GB of RAM? Is that because you have a very large landscape? Once we have multi-threading (in maybe Julia 1.2 or 1.3), it should be easier to use multi-core a lot more effectively. Currently, the multi-processing will balloon RAM usage (it only is useful for smaller grids).

**Comment by ViralBShah** [comment]
Also @glaroc If you are comfortable, it would be great to get a PR.

**Comment by glaroc** [comment]
My grid is 13732 x 9827. I'm not sure why it's consuming so much RAM. 

I'll do a pull request now.

**Comment by ViralBShah** [comment]
Thank you. Can you share your .ini file and data files with @ranjanan to look into it?

**Comment by glaroc** [comment]
Sure I can share the files. Should I send them by email?

**Comment by ranjanan** [comment]
Just an update: I saved @glaroc's matrix and profiled the preconditioner allocation: 
```julia
julia> @time smoothed_aggregation(a)
136.883718 seconds (2.01 M allocations: 147.271 GiB, 3.63% gc time)
```
Most of the allocations however are at [this step](https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/blob/master/src/smoother.jl#L160) and [this step](https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/blob/master/src/aggregation.jl#L85). I have some ideas on how to reduce their memory footprints. More updates soon!

**Comment by ViralBShah** [comment]
Are those sparse matrix multiplies?

**Comment by ranjanan** [comment]
Yes, they are.

**Comment by glaroc** [comment]
Interestingly, I just did a run with a resistance surface of the same size that has values for almost the entire extent (instead of a mask with high resistances outside) and it seems to use about half as much RAM and runs a bit faster.

**Comment by ViralBShah** [comment]
Is this fixed?

**Comment by glaroc** [comment]
Any updates on this issue? I'll need to run a bunch of tests soon with the same raster dimensions.

**Comment by ViralBShah** [comment]
@ranjanan How do you suggest reducing the memory consumption in the sparse matmuls?

**Comment by ranjanan** [comment]
I haven't gotten a chance to work on this yet, but I'll give a good go this weekend. We just need that Galerkin operator `A'*B*A` optimised.

**Comment by ViralBShah** [comment]
Ah yes, that should be easy. @andreasnoack Do we have a general facility to overload these?

**Comment by ViralBShah** [comment]
Yes. That's right.

**Comment by ViralBShah** [comment]
@ranjanan the `A'*B*A` can't be easily calculated without forming an intermediate product. So, no easy savings there. This problem just looks extremely big for 150GB RAM.

**Comment by andreasnoack** [comment]
What are the shapes of `A` and `B`?

**Comment by ViralBShah** [comment]
B is square (nxn). A is rectangular (nxm). n>m. The operation is basically coarsening B.

**Comment by ViralBShah** [comment]
The suggested change is already implemented. Thanks @glaroc

**Comment by glaroc** [comment]
@ViralBShah I'm curious to know whether there has been any progress on the memory issues discussed in this thread?

**Comment by ViralBShah** [comment]
The next plan is to use multi-threading and we hope it will use less memory in parallel (for certain solve modes). On the specific issue of sparse matmul discussed above, we don't expect improvements in that operation. 

Once we have multi-threaded circuitscape, we should do some memory profiling and see if there are other opportunities.
