### ISSUE TITLE
JSExpr: Unsupported `string` expression, "$(e)"JSExpr: Unsupported `string` expression, "$(e)"

### ISSUE THREAD

**Issue by pmillhouser** [Circuitscape/Circuitscape.jl#176]
Hi, longtime Circuitscape 4 user, new user of version 5 on Windows, which has been great for working with larger datasets. After recently starting an advanced run with what I believe to be compliant .asc files, the Circuitscape window proceeds to "Reading maps," but the Julia window shows "JSExpr: Unsupported `string` expression, "$(e)"JSExpr: Unsupported `string` expression, "$(e)"" and the run never seems to complete. Is this a known error with a workaround, or is it more likely to be an issue with my data? The input files are large (400 MB total), but I can give you a Google Drive link to them if that helps. Thanks in advance for any help you can provide, and thanks also for your ongoing work on this excellent program.

**Comment by ranjanan** [comment]
Hi @pmillhouser, are you using the latest Windows binary? I think this is probably a bug with it. Would you mind putting your data on a Google Drive anyway please? It would help me test.

**Comment by pmillhouser** [comment]
Thanks for the quick response!

I believe I am using the latest--the top of the page says "Circuitscape 
5.0," but I believe is used the current 5.4.0 installer. Here's a link 
to the folder with the data:  
https://drive.google.com/open?id=1RBFgyKXAFn1KbRlCkPzVCK8wsj24GMbR The 
resistance surface is ResistBaseCross, the source nodes are 
SummerConcE15, and the grounds are WinterConE15.

Thanks again,

Paul

------ Original Message ------

**Comment by pmillhouser** [comment]
Oh, and here is a screen shot showing the parameters used. I have a 6 
core/ 12 thread processor (i9-8950HK) and used 10 processes, but the 
same issue occurred with processors set at 4 as well.


------ Original Message ------

**Comment by ranjanan** [comment]
So the problem here was Circuitscape was erroring out, but wasn't displaying the error in the UI. I pushed a fix for this here: https://github.com/Circuitscape/CircuitscapeUI.jl/pull/15. This bug fix will be included in the next binary.

**Comment by pmillhouser** [comment]
Thanks, @ranjanan. Do you have any short-term advice for avoiding this error by altering the parameters I use or making a correction to my data?

**Comment by ranjanan** [comment]
@pmillhouser sure, could you tell what your configuration looks like please? What's your resistance map, point file etc?

**Comment by pmillhouser** [comment]
Hi,

THe issue is popping up with the dataset I used earlier. Here's a link 
to the folder with the data:   
https://drive.google.com/open?id=1RBFgyKXAFn1KbRlCkPzVCK8wsj24GMbR The 
resistance surface is ResistBaseCross, the source nodes are 
SummerConcE15, and the grounds are WinterConE15. I'm running Windows 10 
on a Dell XPS 15 with an i9 chip. Let me know if you need any further 
info.

Cheers,

Paul

------ Original Message ------

**Comment by ranjanan** [comment]
@pmillhouser ,for now,  could you try testing with the command line version please? The installation instructions are on the README.

**Comment by pmillhouser** [comment]
Thanks, I will give it a try!

------ Original Message ------

**Comment by pmillhouser** [comment]
Hi @ranjan, sorry to be a bother. I got the command line working but 
with bugs. An initial problem was that the resistance map contained 
zeros, which I replaced with 0.1 (I amusing the same data I previously 
shared). Now I am getting an out of memory error. Changing to connecting 
to 4 neighbors and low memory mode did not help. My machine has 32GB of 
RAM, so I do not believe there is a literal shortage of memory. Here's 
the message I received:

Stacktrace:
  [1] copy(::Array{Float64,1}) at .\array.jl:299
  [2] _deepcopy_array_t(::Any, ::Type, ::IdDict{Any,Any}) at 
.\deepcopy.jl:83
  [3] deepcopy_internal(::Array{Float64,1}, ::IdDict{Any,Any}) at 
.\deepcopy.jl:78
  [4] deepcopy_internal(::Any, ::IdDict{Any,Any}) at .\deepcopy.jl:67
  [5] deepcopy at .\deepcopy.jl:28 [inlined]
  [6] multiple_solver(::Dict{String,String}, 
::SparseArrays.SparseMatrixCSC{Float64,Int32}, ::Array{Float64,1}, 
::Array{Float64,1}, ::Array{Float64,1}) at 
C:\Users\paulm\.julia\packages\Circuitscape\coCa3\src\raster\advanced.jl:264
  [7] advanced_kernel(::Circuitscape.AdvancedData{Float64,Int32}, 
::Circuitscape.RasterFlags, ::Dict{String,String}) at 
C:\Users\paulm\.julia\packages\Circuitscape\coCa3\src\raster\advanced.jl:195
  [8] raster_advanced(::Type, ::Type, ::Dict{String,String}) at 
C:\Users\paulm\.julia\packages\Circuitscape\coCa3\src\raster\advanced.jl:28
  [9] _compute(::Type, ::Type, ::Dict{String,String}) at 
C:\Users\paulm\.julia\packages\Circuitscape\coCa3\src\run.jl:43
  [10] macro expansion at .\util.jl:213 [inlined]
  [11] compute(::String) at 
C:\Users\paulm\.julia\packages\Circuitscape\coCa3\src\run.jl:30
  [12] top-level scope at none:0

Thanks in advance for any advice!

Paul
------ Original Message ------

**Comment by ranjanan** [comment]
Hi @pmillhouser , could you please attach your INI file in the same folder please? I'll just run this and debug. Thanks for reporting this!

**Comment by pmillhouser** [comment]
No worries, thank you for being so responsive. Here's the file.

------ Original Message ------

**Comment by ranjanan** [comment]
@pmillhouser I should have pinged earlier, but I don't see your INI file either on this thread or in the Google Drive link. You may have replied to GitHub directly via email and attached the file, but that doesn't work unfortunately. Could you please add it to the Drive link please? Thank you.

**Comment by pmillhouser** [comment]
I did attach it to my email-oops! Here's a link to it on Google Drive: 
https://drive.google.com/open?id=11WgCLknOAqL_T0OXa7GB7qVOp4rG3-QP

Thanks!

Paul

------ Original Message ------
From: "Paul Millhouser" <paulzm@yahoo.com>
To: "Circuitscape/Circuitscape.jl" 
<reply@reply.github.com>; 
"Circuitscape/Circuitscape.jl" <Circuitscape.jl@noreply.github.com>
Cc: "Mention" <mention@noreply.github.com>
Sent: 2/25/2019 4:27:16 PM
Subject: Re[2]: [Circuitscape/Circuitscape.jl] JSExpr: Unsupported 
`string` expression, "$(e)"JSExpr: Unsupported `string` expression, 
"$(e)" (#176)

**Comment by ranjanan** [comment]
@pmillhouser, I just checked peak memory utilization for your problem, and it doesn't seem too bad. My estimate is that 32 GB of RAM should do. Did you happen to have any other memory intensive processes running at the time?

**Comment by pmillhouser** [comment]
Hi Ranjan,

I was just able to get it to work! I had not had any other apps running 
from the beginning, but I did install a BIOS update from Dell yesterday, 
so I wonder if it patched a memory issue. Fingers crossed it keeps 
working. Thanks for your help!

Paul

------ Original Message ------

**Comment by ranjanan** [comment]
That's great news! Feel free to either open issue or inform me if you have any other issues.
