### ISSUE TITLE
Circuitscape for ArcGis Toolbox

### ISSUE THREAD

**Issue by leefusi** [Circuitscape/Circuitscape.jl#177]
Hi,Is there a user guide for Circuitscape for ArcGis Toolbox?

**Comment by ranjanan** [comment]
See if this helps: https://github.com/Circuitscape/CircuitscapeForArcGIS ? There's a doc file there. Unfortunately there's no user guide but the UI is pretty similar to the standard CS UI

**Comment by leefusi** [comment]
Thank you very much for checking my email during your busy schedule and replying to me. I still can't run successfully in ArcGis based on the website you provided. I really regret that there is no user guide for this.
      I also used CIRCUITSCAPE 4.0 software for calculations, but I also encountered problems because I didn't understand the format of the input file. Here are the steps I took:
     The first step I chose the data type of "Network", the second step I chose Paiwise modeling, then the Inpute resistance data is to convert the raster map into a .txt file in ASCII format, and the Focal node location file uses geographic coordinates. But still can not be used successfully. So I want to ask you if there is a problem with the file format I entered. I also read the CIRCUITSCAPE User Guide, but I still don't understand it. I hope you can answer it.
       Thank you again for your reply, thank you very much. Because of my many problems, I apologize if I disturb your precious time.






At 2019-04-04 20:05:25, "Ranjan Anantharaman" <notifications@github.com> wrote:


See if this helps: https://github.com/Circuitscape/CircuitscapeForArcGIS ? There's a doc file there. Unfortunately there's no user guide but the UI is pretty similar to the standard CS UI

**Comment by ranjanan** [comment]
Hi @leefusi, sorry about the delayed response. I was at a conference, incidentally to talk about Circuitscape. :-)

The plugin assumes you already have Circuitscape installed on your system. Could you tell me where you installed it? @jplatt-B54 informs me that it even assumes you have it installed either in `"ProgramW6432", "ProgramFiles", "ProgramFiles(x86)`.

**Comment by leefusi** [comment]
Hi, you are so kind. I apologize if my question disturbed your meeting. It is my honor to get your reply.
I downloaded it from circuitscape.org. I have already marked the content I downloaded in the red box below.






At 2019-04-17 08:23:51, "Ranjan Anantharaman" <notifications@github.com> wrote:


Hi @leefusi, sorry about the delayed response. I was at a conference, incidentally to talk about Circuitscape. :-)

The plugin assumes you already have Circuitscape installed on your system. Could you tell me where you installed it? @jplatt-B54 informs me that it even assumes you have it installed either in "ProgramW6432", "ProgramFiles", "ProgramFiles(x86).

**Comment by ranjanan** [comment]
Hi @leefusi, happy to help. 

I can't see the red box. You might need to log in to Github and manually upload your screenshot [here](https://github.com/Circuitscape/Circuitscape.jl/issues/177). I don't think Github displays attachments with replies to Github notifications.

**Comment by leefusi** [comment]
oh！I'm sorry that my negligence in operation made you can't see my screenshot. Now I re-upload my screenshot here for your reference. thank you!
![download](https://user-images.githubusercontent.com/49238081/56330506-deb92e00-61ba-11e9-8390-7c863d03a64b.jpg)

**Comment by ranjanan** [comment]
No worries. If you'd like to use the ArcGIS toolbox, could you install the legacy Windows executable please? We're still in the process of getting the ArcGIS toolbox to work with the new version. We'll update the website once we have that working.

**Comment by leefusi** [comment]
Thank you very much for your answers so many times. I will try to install it myself. If there is any problem, please allow me to contact you again. I am also very much looking forward to the arrival of the new version.
Express my gratitude again.




At 2019-04-18 10:14:03, "Ranjan Anantharaman" <notifications@github.com> wrote:


No worries. If you'd like to use the ArcGIS toolbox, could you install the legacy Windows executable please? We're still in the process of getting the ArcGIS toolbox to work with the new version. We'll update the website once we have that working.

**Comment by ranjanan** [comment]
Sure. I'm closing this issue for now, but feel free to open a new one if you have more questions.

**Comment by gjy-del** [comment]
Hi, do you solve this problem? I also meet this question and I don't know how to solve it.
