### ISSUE TITLE
gnarly assistance

### ISSUE THREAD

**Issue by DSO1975** [Circuitscape/Circuitscape.jl#180]
I am trying to download you “gnarly-landscape-utilities” and associated documentation.  Starting at https://circuitscape.org/downloads/ I select https://circuitscape.org/gnarly-landscape-utilities/, and then “Download Gnarly Landscape Utilities here. “ which takes me back to “https://circuitscape.org/downloads/” , of course creating a loop, I imagine I am missing something obvious but not sure what it is and would like to be able to download the utility. Had no problem downloading Circuitscape or Linkage mapper just can’t seem to download the Gnarly utility.  Thanks for you assistance

**Comment by ranjanan** [comment]
Thanks for pointing this out. This was fixed by https://github.com/Circuitscape/www.circuitscape.org/commit/08d2456100acaced6df0747274702f1e9848ddf1. You should now be able to download via the link on the downloads page.

**Comment by DSO1975** [comment]
Thank you, it's seems to be working fine now!
Doug O
