### ISSUE TITLE
Core mapper question 

### ISSUE THREAD

**Issue by DSO1975** [Circuitscape/Circuitscape.jl#185]
Hello
I am trying to run the Core mapper tutorial and continue to get the error below, any insight would be greatly appreciated.  I have checked all directory paths and they seem to be correct.  Thank you for your assistance

  color_index=wb._colors)
  File "C:\Gnarly\CoreMapperDemo\Toolbox\scripts\openpyxl\reader\worksheet.py", line 327, in read_worksheet
    fast_parse(ws, xml_source, shared_strings, style_table, color_index)
  File "C:\Gnarly\CoreMapperDemo\Toolbox\scripts\openpyxl\reader\worksheet.py", line 315, in fast_parse
    parser.parse()
  File "C:\Gnarly\CoreMapperDemo\Toolbox\scripts\openpyxl\reader\worksheet.py", line 94, in parse
    dispatcher[tag_name](element)
  File "C:\Gnarly\CoreMapperDemo\Toolbox\scripts\openpyxl\reader\worksheet.py", line 291, in parse_data_validation
    dv = parser(tag)
  File "C:\Gnarly\CoreMapperDemo\Toolbox\scripts\openpyxl\worksheet\datavalidation.py", line 225, in parser
    dv = DataValidation(**element.attrib)
TypeError: __init__() got an unexpected keyword argument '{http://schemas.microsoft.com/office/spreadsheetml/2014/revision}uid'

Failed to execute (CoreMapper2).

**Comment by ViralBShah** [comment]
This should be filed in the python circitscape repo.

**Comment by DSO1975** [comment]
That reply wasn't very helpful i.e. where is the python circitscape repo.
I am new at this, you probably have been doing this a while so more
complete and informative answers would be greatly appreciated

Thank you
Doug Ouren

**Comment by ViralBShah** [comment]
Please file here: https://github.com/Circuitscape/Circuitscape

The python version is unmaintained at this point, but it would be good to have the issue filed anyways in case others run into it.

**Comment by DSO1975** [comment]
So does your response mean that the Core mapper tutorial does not work?  Is
there an alternative? Just trying to figure out your software and tutorials
are helpful.  Thanks

**Comment by Kim-Hall** [comment]
Hi Doug - the team here did not actually build the Core Mapper tutorial for Gnarly - that was Brad McRae who passed away in 2017, probably also with help from the other Gnarly co-authors.  If you are still interested/having issues, I can likely connect you to them.
