### ISSUE TITLE
Documentation Clarification

### ISSUE THREAD

**Issue by simon-tarr** [Circuitscape/Circuitscape.jl#186]
Hello, I was wondering if someone could help clarify documentation definitions between versions 4 and 5.x of Circuitscape. The documentation at https://circuitscape.org/docs/ is for v4.0 and was last updated 5 years ago. While excellent for the general theoretical underpinnings, I am struggling to reconcile the input settings between the old (v4.x) GUI versions of the application and the Julia command line version of the software. 

There are few differences in the GUI inputs/terminology between v4 and v5, so there's little to be misunderstood there. However, the .ini file required by Julia has different names for the GUI inputs. I wanted to fully understand how the GUI inputs map to the .ini file.

For example, in the GUI there are two main inputs - the resistance map and the focal nodes map.  In the example .ini files in `Circuitscape.jl\test\input\raster\` there appear to be three inputs: a `point_file` (e.g. `point_file = input/raster/pairwise/1/points.asc`), a `polygon_file` (e.g. `polygon_file = input/raster/pairwise/1/polygons.asc`) and a `habitat_file` (e.g. `habitat_file = input/raster/pairwise/1/cellmap.asc`).

I'm guessing that the `habitat_file` in .ini maps to the 'focal node locations' in the GUI? And that the `point_file` maps to the 'input resistance map' in the GUI? 

I apologise if there is full documentation explaining the Julia interface already in existence but I can't find it on the Circuitscape website. If it is available somewhere, I would be grateful if someone could point me in the right direction.

Many thanks.

**Comment by ranjanan** [comment]
Hi @simon-tarr , 

1. You're right, the documentation on the website needs to be updated for v5. 
2. Habitat file refers to the resistance surface. The only reason it's called `habitat_file` is for legacy reasons. We'd like this upgraded version to behave exactly like the previous versions, and INI files generated by previous GUIs usually. 
3. Polygon file is not required to run Circuitscape. In most cases, people don't use it. `use_polygons = false` should be fine. Polygons refer to "patches" on the graph that are short circuited, that is, there is no zero resistance in travelling between those cells. Hence, they are collapsed into one node in the graph.
4. The point file refers to focal nodes, points of interest between which you'd like to measure connectivity.
5. `habitat_map_is_resistances` refers to whether the map you've specified the path to is a resistance map or a permeability (or conductance map), that is, higher values correspond to higher resistance or lower resistance. 

I think I have covered all your questions in these points, happy to offer further clarification. Again, apoligies for my delays. Once the semester is done by next week, I'll be much more responsive!

**Comment by simon-tarr** [comment]
Hi @ranjanan no problem, thanks for getting back to me! I know how manic end of semesters can be so I appreciate you taking the time to respond to the above questions.

**Comment by ranjanan** [comment]
No problem, do you have any more questions on this vein? If not, I'll close this issue.

**Comment by simon-tarr** [comment]
No, that's everything that I can think of for now. Thanks for responding.
