### ISSUE TITLE
Two Issues: Memory Error and Not working on my desktop

### ISSUE THREAD

**Issue by kashacatie** [Circuitscape/Circuitscape.jl#191]
Hi I hope you will have time to help. We are using the arcgis toolbox.
First issue we are encountering. We are running CS to check for connectivity of species in a country. The first resistance and point asc and resistance raster is created. After that we get the memory error. Is there away we can run the entire country of Liberia and not get the memory error.

Second issue: I have installed CS on my home desktop computer and the toolbox. My computer at home may have enough memory. When I open the tool I have a red error x at the top. I have installed python, CS version window 64, my arcmap is version 10.6.1. Please help me with what is missing.

Thank you,
Catherine

**Comment by ranjanan** [comment]
@kashacatie could you attach appropriate screenshots for the issues?

**Comment by ViralBShah** [comment]
I think this issue is about the python version, so closing here.
