### ISSUE TITLE
Blank screen on GUI after running main executable

### ISSUE THREAD

**Issue by f-tonini** [Circuitscape/Circuitscape.jl#192]
Hi there,

I am having issues with Circuitscape v5 (beta) when trying to start the GUI after closing it the first time. I am attaching a screenshot of the blank screen I see. The first time I run the program everything seems to work, but not after closing and re-opening the software

![Annotation 2019-07-15 091838](https://user-images.githubusercontent.com/1470540/61231324-2a5f7300-a6e9-11e9-9725-e854c06f57af.png)

**Comment by ViralBShah** [comment]
I suspect the GUI is buggy. We are planning to remove it from the Julia version for now and request people use the command line version, and document the process better. Simultaneously, we will also figure out how to improve the UI and make it robust.

Can you tell us for the record here which version of windows you are using, and if it is 32-bit or 64-bit?

**Comment by f-tonini** [comment]
Sure, I am testing it on a Windows Server 2012 R2 (thus 64 bit). Should I let our customers about using it via the command line then in the meantime?

**Comment by ViralBShah** [comment]
Yes that would be best for now. Thank you.

**Comment by ViralBShah** [comment]
It is recommended to use the Julia version through the command line for now. We have a bunch of overhauls to do before we can come back to the GUI.

**Comment by ViralBShah** [comment]
@ranjanan Perhaps we can replace the beta binaries on the downloads page with Julia and package installation directions?

**Comment by ranjanan** [comment]
Yes, we can leave instructions on installing the package and building an INI file.

**Comment by ranjanan** [comment]
Should I remove the links to the GUI? I'm tempted to keep them online too because they do work for some people, even if they do have some issues.

**Comment by ViralBShah** [comment]
How about clearly articulate the command line instructions for the Julia REPL (on the downloads page) and say the new GUI is experimental.

**Comment by vlandau** [comment]
Should we close given the new INIBuilder and deprecation of the GUI?
