### ISSUE TITLE
Error : UndefVarError : warn not defined

### ISSUE THREAD

**Issue by dlecourstessier** [Circuitscape/Circuitscape.jl#193]
Hi Everyone one !

I am currently having some issues running Circuitscape analysis with Julia 1.1.0. 
I always get the error : warn not defined

**Here is the script I get :** 

julia> compute("/home/dlecourstessier/dlt/Connectivite/Zone_beta.ini")
[ Info: 2019-08-06 18:16:16 : Logs will recorded to file: log_file
[ Info: 2019-08-06 18:16:16 : Precision used: Double
[ Info: 2019-08-06 18:16:16 : Reading maps
[ Info: 2019-08-06 18:17:16 : Resistance/Conductance map has 31108432 nodes
ERROR: UndefVarError: warn not defined

**And here is my initiation files:**
[Options for advanced mode]
ground_file_is_resistances = True
remove_src_or_gnd = keepall
ground_file = E:\Focal_node_MT.asc
use_unit_currents = False
source_file = E:\Contour_MT.asc
use_direct_grounds = False

[Mask file]
mask_file = None
use_mask = False

[Calculation options]
low_memory_mode = False
parallelize = True
solver = cg+amg
print_timings = True
preemptive_memory_release = False
print_rusages = False
max_parallel = 5

[Short circuit regions (aka polygons)]
polygon_file = (Browse for a short-circuit region file)
use_polygons = False

[Options for one-to-all and all-to-one modes]
use_variable_source_strengths = False
variable_source_file = None

[Output options]
set_null_currents_to_nodata = False
set_focal_node_currents_to_zero = False
set_null_voltages_to_nodata = False
compress_grids = True
write_cur_maps = 1
write_volt_maps = False
output_file = /home/dlecourstessier/dlt/Connectivite/Connectivite_zone_beta_BLQ.asc
write_cum_cur_map_only = TRUE
log_transform_maps = False
write_max_cur_maps = False

[Version]
version = 4.0.5

[Options for reclassification of habitat data]
reclass_file = (Browse for file with reclassification data)
use_reclass_table = False

[Logging Options]
log_level = INFO
log_file = /home/dlecourstessier/dlt/Connectivite/Connectivite.log
profiler_log_file = None
screenprint_log = False

[Options for pairwise and one-to-all and all-to-one modes]
included_pairs_file = /home/dlecourstessier/dlt/Connectivite/Aires_protegees_zone_beta_null.asc
use_included_pairs = True
point_file = /home/dlecourstessier/dlt/Connectivite/Aires_protegees_zone_beta_null.asc

[Connection scheme for raster habitat data]
connect_using_avg_resistances = False
connect_four_neighbors_only = False

[Habitat raster or graph]
habitat_map_is_resistances = True
habitat_file = /home/dlecourstessier/dlt/Resistance/Resistance_zone_beta_BLQ.asc

[Circuitscape mode]
data_type = raster
scenario = all-to-one

**Do you have any ideas of the problems or solutions ??**

**Thanks a lot !**

**Comment by ranjanan** [comment]
The fix is on the master branch but not in the release. I'll just make a quick release and notify you.

**Comment by ViralBShah** [comment]
done.

**Comment by ranjanan** [comment]
@dlecourstessier just execute `using Pkg; Pkg.update()` at the Julia REPL, it should update your version of Circuitscape and you should see your package updated.

**Comment by dlecourstessier** [comment]
Yes ! I did it and it is now running !! Thank you very much !
