### ISSUE TITLE
ERROR: Failed to read habitat map. There may be errors in your file.

### ISSUE THREAD

**Issue by dlecourstessier** [Circuitscape/Circuitscape.jl#198]
Hi ! 

I am trying to run an analyse in mode "advanced", but it seems that there is an error in my habitat (resistance) map. However, it was working last week (I've change few thing in the source file since, which is why I have to re-run the analyses) and doesn't anymore... would you have an idea on what's going on ? 

Here is the link to the files ; https://drive.google.com/drive/folders/1OkB65t-LorPOA40JGSoLohzsK4EljpFm?usp=sharing 

Thanks again and I hope it is the last time I bother you !

**Comment by ViralBShah** [comment]
Sorry - we did not respond. Did this eventually work out?

**Comment by dlecourstessier** [comment]
Hi !

I work with Timothée Poisot, so we are now using Omniscape and it works !!
Thanks for asking 🙂


Daphnée Lecours Tessier
Candidate à la Maîtrise /  M Sc. candidate
Laboratoire d'écologie computationnelle de Timothée Poisot
Université de Montréal, Département des Sciences Biologiques
Pavillon Marie Victorin, C.P. 6128, succ. Centre-ville Montréal, Québec H3C 3J7 Canada


________________________________
De : Viral B. Shah <notifications@github.com>
Envoyé : 21 novembre 2019 15:32
À : Circuitscape/Circuitscape.jl <Circuitscape.jl@noreply.github.com>
Cc : dlecourstessier <d.lecourstessier@hotmail.com>; Author <author@noreply.github.com>
Objet : Re: [Circuitscape/Circuitscape.jl] ERROR: Failed to read habitat map. There may be errors in your file. (#198)


Sorry - we did not respond. Did this eventually work out?
