### ISSUE TITLE
ERROR: DimensionMismatch

### ISSUE THREAD

**Issue by MarioInTaipei** [Circuitscape/Circuitscape.jl#199]
Hi,
I ran a relatively large file (11M connections between 3960000 nodes ) in Circuitscape 5.5.4 and Circuitscape 4.0.5 using the same .ini file. 
It works well in 4.0.5 generating 216764 entries in the output_voltages.txt.
In 5.5.4 it generates the error: "tried to assign 3960001-element array to 216764×1 destination".

**Comment by ranjanan** [comment]
I see, thanks for pointing this out. Could you test this with the master
branch of Circuitscape too? It might be fixed there.

Best,
Ranjan Anantharaman

**Comment by MarioInTaipei** [comment]
I tried the master branch and get the same error.

Best,

Mario

**Comment by ViralBShah** [comment]
Could you share your input files and the ini file?

**Comment by MarioInTaipei** [comment]
Hi,
I found that the error happens regardless of input file size. I attached the pairs and ini (I had to add a.txt ending to upload it to Github)
[pairs.txt](https://github.com/Circuitscape/Circuitscape.jl/files/3762589/pairs.txt)
[ground.txt](https://github.com/Circuitscape/Circuitscape.jl/files/3762590/ground.txt)
[source.txt](https://github.com/Circuitscape/Circuitscape.jl/files/3762591/source.txt)

[output.ini.txt](https://github.com/Circuitscape/Circuitscape.jl/files/3762593/output.ini.txt)

**Comment by ranjanan** [comment]
@MarioInTaipei I am able to reproduce this error, I'll come up with a fix soon. I see that you're using network mode? Could I ask you about your application and why you choose to use network mode instead of raster mode?

**Comment by MarioInTaipei** [comment]
Hi,
thank you for the update. We are using circuitscape to solve complex  
networks that represent conductive pathways in materials and since these  
are 3D (or even more complicated) we cannot discretize them into a raster.

Best regards,

Mario

**Comment by ViralBShah** [comment]
That's fascinating. Any pointers to your work or papers would be fun to look at.

**Comment by MarioInTaipei** [comment]
We are currently in the process of submitting the paper and I will update  
you as soon as it comes out.

**Comment by ranjanan** [comment]
@MarioInTaipei I am currently in the process of finishing up my semester (and all the associated exams), and I will be able to work on this a little before Christmas time. I hope this does not get in the way of you submitting your work.

**Comment by MarioInTaipei** [comment]
Hi,
no worries, getting this to work is only a bonus. Good luck with your  
exams!

**Comment by ranjanan** [comment]
@MarioInTaipei I have been working on a fix, and got the following outputs. Could you verify that these outputs look right and match Circuitscape 4? if so, I'll push this fix. 

[output_voltages.txt](https://github.com/Circuitscape/Circuitscape.jl/files/4034612/output_voltages.txt)
[output_node_currents.txt](https://github.com/Circuitscape/Circuitscape.jl/files/4034613/output_node_currents.txt)
[output_branch_currents.txt](https://github.com/Circuitscape/Circuitscape.jl/files/4034615/output_branch_currents.txt)

Thanks!

**Comment by MarioInTaipei** [comment]
Hi,
the results are spot on except for one issue: The first element (1, 0)  
should not be there since it makes the array one element too long and is  
not the correct voltage for the first node (i.e. 2, 20.7) is. Also, the  
format of the first column used to be integer (1) but now is float (1.0).  
This is not a problem for our purpose but might cause problem with others?

So, even in the current form the fix is solving all our problems!

Thank you.

Best regards,

Mario
