### ISSUE TITLE
GZip broken for Windows in Julia 1.3, so Circuitscape (and Omniscape) also broken

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Circuitscape.jl#203]
libz was renamed in Julia 1.3 which caused GZip to no longer work. 

I reached out to the GZip devs a couple of weeks ago and they have a pull request (not yet merged), but I haven't heard anything in a while.

With the release of Julia 1.3 last night, this means that Circuitscape is now also broken in Julia 1.3 because of it's dependency on GZip. Omniscape is *also* broken now because of the dependency on Circuitscape. If possible, it might be best to remove Circuitscape's GZip dependency to avoid this issue altogether. I'm not sure how quickly the GZip devs are going to get the fix merged and release a patch. Hopefully soon now that Julia 1.3 has been released...

 Here's the [issue](https://github.com/JuliaIO/GZip.jl/issues/83) and [pull request](https://github.com/JuliaIO/GZip.jl/issues/83) for reference.

**EDIT**
This affects **windows systems only**

cc @ranjanan and @ViralBShah

**Comment by vlandau** [comment]
Okay, the fix was just merged with the master of GZip, so once a patch is released, we'll need to updated the GZip compat entry for Circuitscape. I can do a PR to do that. I know @ranjanan is very busy with other things at the moment.

**Comment by ViralBShah** [comment]
A PR is appreciated. Do you have commit access to this package?

**Comment by vlandau** [comment]
I do. I'll put in a PR to merge to master. I've got the fix on the [GZip-fix branch](https://github.com/Circuitscape/Circuitscape.jl/tree/GZip-fix) now, and it's parent commit is the v5.5.4 tag, so we could tag a new patch release from GZip-fix immediately.

Here's my commit (also see an added comment): https://github.com/Circuitscape/Circuitscape.jl/commit/8c920fd
