### ISSUE TITLE
Error: zero resistance values are not currently supported for habitat maps. Use a shor circuit region file instead

### ISSUE THREAD

**Issue by Jinyu8579** [Circuitscape/Circuitscape.jl#210]
When I run a .asc file with zero resitance values using Circuitscape v5.5.5 on julia 1.3.0, it reports error "Error: zero resistance values are not currently supported for habitat maps. Use a shor circuit region file instead". How can I set values in the .ini file for .asc file with zero resitance values? I am very new to Julia and Circuitscape.jl, so please forgive a very basic question. I am so  anxious that the problem hasn't been solved.

**Comment by merijnvdb** [comment]
@Jinyu8579  how did you solve this? I have the same error
