### ISSUE TITLE
Please reopen if the issue persists.

### ISSUE THREAD

**Issue by frederikvand** [Circuitscape/Circuitscape.jl#215]
Please reopen if the issue persists.

_Originally posted by @ViralBShah in https://github.com/Circuitscape/Circuitscape.jl/issues/214#issuecomment-570367189_

Can't reopen the issue: https://github.com/isaacs/github/issues/583
Original reporter should be able to reopen a closed issue

**Comment by ViralBShah** [comment]
I have reopened #214. Closing this one.
