### ISSUE TITLE
Experiment with PARDISO solvers from MKL

### ISSUE THREAD

**Issue by ViralBShah** [Circuitscape/Circuitscape.jl#218]
Now in BB as well:

https://github.com/JuliaSparse/Pardiso.jl/pull/56

**Comment by ViralBShah** [comment]
@ranjanan Can you note your findings here?

**Comment by ViralBShah** [comment]
@ranjanan reports:
On Antarctic, MKL Pardiso about 20% faster than CHOLMOD using the defaults. Antarctic has 20 cores, which PARDISO is able to utilize.

**Comment by ViralBShah** [comment]
![image](https://user-images.githubusercontent.com/744411/74607843-4295d700-50aa-11ea-9e0a-ccdff43d7c73.png)

**Comment by ViralBShah** [comment]
@vlandau Can you try out using the MKL Pardiso solver in OmniScape? Does it help?

**Comment by vlandau** [comment]
Definitely! So this is a different method from CHOLMOD, and it works in Advanced mode?

**Comment by ViralBShah** [comment]
Yes, it should work everywhere. It is just an alternative solver - but it is a sparse direct solver like cholmod. Probably need to set number of threads to 1 in parallel mode (by looking at Intel MKL docs).

**Comment by vlandau** [comment]
Does that mean I can't run multiple solvers in parallel with this method in Omniscape? (I use multithreading)

**Comment by ViralBShah** [comment]
You should be able to. Generally Pardiso will try to use all the cores, so you have the over subscription problem. So some environment variable probably should be set so that each Julia process runs pardiso only on one core, when in parallel.

**Comment by vlandau** [comment]
Okay I see -- sort of similar to over subscription due to BLAS parallelization. I'll look into this!
