### ISSUE TITLE
New GUI using Gtk?

### ISSUE THREAD

**Issue by ranjanan** [Circuitscape/Circuitscape.jl#228]
Building it with Glade and GtkBuilder might be the way to go. Should just be a few days of work. Lower priority as compared to multi-threading but the excellent Artifacts system seems to let us ship such a complex library and get it to work.

**Comment by ViralBShah** [comment]
Tk.jl might perhaps be simpler.

**Comment by ViralBShah** [comment]
Dash.jl or Tk.jl is perhaps the way to do this. Closing for now.
