### ISSUE TITLE
Circuitscape in Julia unable to process a 1.4 Billion pixel landscape

### ISSUE THREAD

**Issue by indranil-wii** [Circuitscape/Circuitscape.jl#232]
Hello,
I am new to Circuitscape in Julia and also Julia per se. I am trying to run Circuitscape on a landscape which is 37946 X 36946 pixels of 30m spatial resolution. I have scaled the conductance values from 1 to 100.

The specifications of my system is:
2 X Intel Xeon Gold 6136 so total 24 physical processor cores
128GB RAM.

When I tried parallel processing using 10 cores, my system ran out of memory. Then I disabled parallel processing and ran it. First it took a lot of time to read the maps even on the system that I am using, which I thought has a good specification. Then it gave this new error:

ArgumentError: the index type Int32 cannot hold 4075170303 elements; use a larger index type

I am attaching a screen shot of the console.

Regards,
Indranil.

![Julia Run Fail](https://user-images.githubusercontent.com/52761050/80853974-3d303d80-8c52-11ea-9dc6-6a9725f5e253.PNG)

**Comment by ViralBShah** [comment]
1.4 billion just sounds really big. You should try with 1 core first.

**Comment by indranil-wii** [comment]
Hi Viral. Thanks for the reply. I have upgraded my RAM to 348GB now. Still I will go with 1 core first as you suggested. Issue #200 provided some help. Will be using the following to use 64 bit indexing:
`use_64bit_indexing = true`

**Comment by ViralBShah** [comment]
Great. Parallel processing also needs extra memory. So the larger the problem, the more you have to start slowly and push the parallelism.

**Comment by indranil-wii** [comment]
Hi Viral. Ran the same landcape with 1 core and 64 bit indexing. FAILED !! OutOfMemoryError()

My conductance surface is 10.5GB and the core area raster is 7.69GB. I am unable to understand why 348GB RAM is not enough.

Attaching screenshot. Also, this is being run on Windows 10 Pro (if that information is of any use). I have access to a Linux machine as well. I can swap the RAM modules and try on that if that helps.

![Capture](https://user-images.githubusercontent.com/52761050/80899205-1db91380-8d2b-11ea-9fe1-20c8c06122ca.PNG)

**Comment by ViralBShah** [comment]
Which solver are you using? Make sure it is cg+amg.

**Comment by ViralBShah** [comment]
The underlying graph and soccer data structures easily take 10x-20x more memory than your surface. 

We have done reasonably careful memory profiling, but there may be more options.

**Comment by indranil-wii** [comment]
> 
> 
> Which solver are you using? Make sure it is cg+amg.

I was using the cholmod solver. I will give it a try with cg+amg.

**Comment by ViralBShah** [comment]
Oh yeah - cholmod will not work for anything more than 1-10M cell landscapes. Maybe we should print a warning.

**Comment by indranil-wii** [comment]
Was amazed to see the memory gradually maxing out and the application stopping with a OutOfMemoryError(). I have resampled my surfaces from 30m to 100m and saw a dramatic reduction in size. Now both the habitat and node rasters are less than 1GB. Trying again with resampled image.

![Capture2](https://user-images.githubusercontent.com/52761050/80933277-ae056000-8de0-11ea-8239-715bbbf91bd4.PNG)

**Comment by indranil-wii** [comment]
Hi Viral, with reduced file sizes things seem to be running, even with 4 cores in parallel !! Processing time in each step has drastically reduced too along with a much lower memory footprint.

**Comment by ViralBShah** [comment]
The old files are fully compatible. Yes, we should document these things. Beyond what I shared here, there really are not many more things. Would you be able to submit a PR?

**Comment by indranil-wii** [comment]
I am new to GitHub as well, so I will need to read up about pull requests before I am able to do so. However, I can easily prepare a template ini file with annotation.

**Comment by vlandau** [comment]
Close and move to #233?

**Comment by indranil-wii** [comment]
Once I resampled and made my landscape smaller in MBs, Circuitscape in Julia started working without any error. In fact the analysis that I started is still running. It has 19,900 pairs, and at this rate, I calculated, it will take 200 days!! I am running in 4 cores in parallel and about 50% of 384GB memory usage.

My question is how does this parallelism work? I was thinking that each core will be processing a pair at a time, so 4 pairs will be processed at the same time. But I don't see that from the logs. I wanted to use parallelism to save me some time.

This is when the job started:
  
![Capture1](https://user-images.githubusercontent.com/52761050/81036547-1f1a4580-8ebd-11ea-9101-825807af8a9d.PNG)

And this is right now:
![Capture2](https://user-images.githubusercontent.com/52761050/81036568-2f322500-8ebd-11ea-960c-21c916e538c6.PNG)

**Comment by ViralBShah** [comment]
We need to move to the multi-threading version of circuitscape that will allow more parallelism and lesser memory. But it is not even ready to try yet, since we are running into some issues.

For now, you can make your problem even smaller and increase parallelism, and/or reduce the number of pairs. What mode are you using? Simple pairwise resistance, no polygons? The simpler you can make it the faster it will go.

**Comment by ViralBShah** [comment]
> Close and move to #233?

We can keep this open to discuss the particular problem at hand.

**Comment by vlandau** [comment]
Are you using an include pairs file to specify which pairs you want connected? That can affect the scheduler and make parallelism less efficient (#165)

**Comment by indranil-wii** [comment]
I am using pairwise mode and I am not using an include pairs file. I have made a raster from the polygon shapefile of the core area polygons and mentioned the path of the file in the "point_file" option. The contents of the ini file are as below. Please tell me if anything is extra or if I am missing anything.

**[Options for advanced mode]**
ground_file_is_resistances = True
source_file = None
remove_src_or_gnd = keepall
ground_file = None
use_unit_currents = False
use_direct_grounds = False

**[Calculation options]**
low_memory_mode = False
solver = cg+amg
print_timings = True
preemptive_memory_release = True

**[Options for pairwise and one-to-all and all-to-one modes]**
included_pairs_file = None
use_included_pairs = False
point_file = D:\folder\raster_of_core_polygons.asc

**[Output options]**
write_cum_cur_map_only = True
log_transform_maps = False
output_file = D:\folder\habitat_raster.out
write_max_cur_maps = False
write_volt_maps = False
set_null_currents_to_nodata = False
set_null_voltages_to_nodata = False
compress_grids = False
write_cur_maps = True
set_focal_node_currents_to_zero = True

**[Short circuit regions (aka polygons)]**
use_polygons = False
polygon_file = None


**[Connection scheme for raster habitat data]**
connect_four_neighbors_only = False
connect_using_avg_resistances = False

**[Habitat raster or graph]**
habitat_file = D:\cirascii\resistance.asc
habitat_map_is_resistances = True

**[Options for one-to-all and all-to-one modes]**
use_variable_source_strengths = False
variable_source_file = None

**[Version]**
version = unknown

**[Mask file]**
use_mask = False
mask_file = None

**[Circuitscape mode]**
data_type = raster
scenario = pairwise
parallelize = True
max_parallel = 8
use_64bit_indexing = True
log_resource_usage_info = True
`

**Comment by vlandau** [comment]
Nothing jumps out to me as problematic in your .ini

There seems to be something going on with the task scheduler. @ranjanan or @ViralBShah would there be any reason that the scheduler would behave differently in Julia 1.4?

I'm seeing similar output patterns (that imply no parallel processing) for a specific test on Julia 1.4 as well.

```
[ Info: Testing sgVerify5
[ Info: 2020-05-05 16:57:56 : Precision used: Double
[ Info: 2020-05-05 16:57:56 : Starting up Circuitscape to use 2 processes in parallel
[ Info: 2020-05-05 16:57:59 : Reading maps
[ Info: 2020-05-05 16:57:59 : Resistance/Conductance map has 14 nodes
[ Info: 2020-05-05 16:57:59 : Total number of pair solves = 10
[ Info: 2020-05-05 16:57:59 : Solving pair 1 of 10
[ Info: 2020-05-05 16:57:59 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:57:59 : Graph has 10 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:57:59 : Time taken to construct preconditioner = 9.7036e-5 seconds
[ Info: 2020-05-05 16:57:59 : Time taken to construct local nodemap = 2.194e-6 seconds
[ Info: 2020-05-05 16:58:04 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:04 : Time taken to solve linear system = 0.003566931 seconds
[ Info: 2020-05-05 16:58:04 : Time taken to write voltage maps = 0.019530949 seconds
[ Info: 2020-05-05 16:58:04 : Time taken to write current maps = 0.319035418 seconds
[ Info: 2020-05-05 16:58:04 : Solving pair 2 of 10
[ Info: 2020-05-05 16:58:04 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:04 : Graph has 11 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:04 : Time taken to construct preconditioner = 4.5504e-5 seconds
[ Info: 2020-05-05 16:58:04 : Time taken to construct local nodemap = 2.733e-6 seconds
[ Info: 2020-05-05 16:58:04 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:04 : Time taken to solve linear system = 0.003556326 seconds
[ Info: 2020-05-05 16:58:04 : Time taken to write voltage maps = 0.071955798 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 0.289728361 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 3 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 11 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 5.6052e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.678e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.3273e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 9.7962e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 8.8905e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 4 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 11 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 4.4383e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.652e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.3623e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 6.7633e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 8.0678e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 5 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 11 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 3.3565e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.668e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.3035e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 7.5914e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 8.9053e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 6 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 11 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 2.8466e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.37e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.1571e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 5.1227e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 7.4459e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 7 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 11 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 4.1619e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.437e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 9.907e-6 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 5.9589e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 6.1835e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 8 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 12 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 4.0396e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.651e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.0052e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 5.0666e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 7.7561e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 9 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 12 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 4.1554e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.481e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.0198e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 6.8243e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 6.2656e-5 seconds
[ Info: 2020-05-05 16:58:05 : Solving pair 10 of 10
[ Info: 2020-05-05 16:58:05 : Solver used: AMG accelerated by CG
[ Info: 2020-05-05 16:58:05 : Graph has 12 nodes, 2 focal points and 1 connected components
[ Info: 2020-05-05 16:58:05 : Time taken to construct preconditioner = 2.7234e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to construct local nodemap = 2.451e-6 seconds
[ Info: 2020-05-05 16:58:05 : Scheduling pair 1 of 1 to be solved
[ Info: 2020-05-05 16:58:05 : Time taken to solve linear system = 1.0929e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write voltage maps = 7.0516e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to write current maps = 7.8654e-5 seconds
[ Info: 2020-05-05 16:58:05 : Time taken to complete job = 5.912580516
[ Info: Testing sgVerify5_cum_curmap.asc
[ Info: Test sgVerify5_cum_curmap.asc passed
```

**Comment by ranjanan** [comment]
@indranil-wii it seems that your point file contains polygons. That is, you have large regions you'd like to collapse into one point. We do not support parallelism (yet) in this mode because you have to keep recomputing the graph datastructure for every solve and this would take *a lot* more memory if done in parallel (imagine holding 4 of these large graph datastructures in memory). 

Is there a way you can make your point files have points instead of regions? (Use the centroids of those focal regions, for example. @vlandau you may have better advice on this). If you do this, the parallelism will work and your problem may be solved faster.

**Comment by vlandau** [comment]
> Use the centroids of those focal regions, for example

I would do exactly that.

**Comment by indranil-wii** [comment]
I could do that to simplify the problem and conceptually too it seems fine to use the centroids, However, there are practical problems. The corridors won't be mapped right. On ground the movement of animals is not directed towards the centroid of a park from outside but towards the nearest place on the perimeter. So I have to preserve the actual shape of the core area polygon.

**Comment by vlandau** [comment]
You could set the sources to be centroids and set your original polygons as short circuit regions. @ranjanan would that work with parallelism?

**Comment by ViralBShah** [comment]
@indranil-wii Can we request you to take the learnings from this discussion and add them to the README for now https://github.com/Circuitscape/Circuitscape.jl/blob/master/README.md? 

There is a little pen next to the README file, so you can just edit the file and submit some text. We can have a new section called - Notes for using Circuitscape on very large grids.

**Comment by indranil-wii** [comment]
> 
> 
> @indranil-wii Can we request you to take the learnings from this discussion and add them to the README for now https://github.com/Circuitscape/Circuitscape.jl/blob/master/README.md?
> 
> There is a little pen next to the README file, so you can just edit the file and submit some text. We can have a new section called - Notes for using Circuitscape on very large grids.

Sure, I can do that.

**Comment by indranil-wii** [comment]
> 
> 
> @indranil-wii it seems that your point file contains polygons. That is, you have focal regions you'd like to collapse into one point in your point file. We do not support parallelism (yet) in this mode because you have to keep recomputing the graph datastructure for every solve and this would take _a lot_ more memory if done in parallel (imagine holding 4 of these large graph datastructures in memory).
> 
> Is there a way you can make your point files have points instead of regions? (Use the centroids of those focal regions, for example. @vlandau you may have better advice on this). If you do this, the parallelism will work and your problem may be solved faster.

I would like to try once with point files as my core area. However, I have never done that before. How do I format my core area file then, if they are to be points?

**Comment by ViralBShah** [comment]
The suggestion is not use the core area / polygons at all, and just compute resistance between pairs of central points in all your core areas.

**Comment by indranil-wii** [comment]
> 
> 
> The suggestion is not use the core area / polygons at all, and just compute resistance between pairs of central points in all your core areas.

Yes, I understand. In what format do I supply the central points file?

**Comment by vlandau** [comment]
> Yes, I understand. In what format do I supply the central points file?

This is in the [documentation](https://circuitscape.org/docs/). See the section titled "Focal node location and data type". Focal points can be in the same ASCII format. They just must be only one pixel each.

**Comment by ranjanan** [comment]
> @ranjanan would that work with parallelism?

Should work.

**Comment by Kim-Hall** [comment]
Just read through this and while I can't help on the technical issues, I'm curious to know what is being modeled here, given there is such a huge number of pairs to connect.  If you are connecting "everything to everything" maybe Omniscape would be worth a try?  While Vincent is the expert, I'm happy to do a zoom overview of that tool and show you some examples to see if it might fit your problem.  I'm assuming similar issues would arise given you still have a gigantic grid, but for that tool you would only be connecting "everything to everything" in a moving window, not trying to directly connect pairs that are long distances apart.

**Comment by vlandau** [comment]
This issue appears to have been sufficiently addressed and gone somewhat stale. I'm going to close for now.
