### ISSUE TITLE
More issues with opened files on Mac

### ISSUE THREAD

**Issue by vlandau** [Circuitscape/Circuitscape.jl#241]
I think it may have to do with readdlm possibly leaving files open on Mac. The error occurred during tests during the output verification stage, which used readdlm. It seems to be inconsistent, with the "too many open files error" only happening occasionally. I'll append this with a stacktrace if the error gets triggered again.

cc @ranjanan

**Comment by ViralBShah** [comment]
I had tracked a bunch of these down a while back. I had found some opens for which Circuitscape was not closing things. I doubt it is a readdlm issue - but you never know.

**Comment by ViralBShah** [comment]
See 614b86c5ad9553126909949cae8b2d96f01cb033 and #212 and #221

**Comment by vlandau** [comment]
Yeah -- @ranjanan and I had to go through this again with the latest tif support PR, but I figured out  that read_raster was leaving files open (it has since been fixed).

Ah yes, #212 above is exactly what happened this time (I lost the stacktrace for the failure I got, but it was the same as #212). I guess I can close this for now since it's a dupe of #212. Sorry about that!
