### ISSUE TITLE
Get CI to pass

### ISSUE THREAD

**Issue by ViralBShah** [Circuitscape/Circuitscape.jl#245]
We should get CI to pass before tagging a new version.

I think given the tiff stuff, all the dependency updates, and the pmap fix (among other things), we should go to 6.0.

**Comment by vlandau** [comment]
I think the issue with CI not passing on Windows has to do with SharedArrays right? I got the sense that it won't be solved until multithreading is implemented from @ranjanan.

**Comment by vlandau** [comment]
Looks like AlgebraicMultigrid v0.3 [requires Julia 1.4 or greater](https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/blob/master/Project.toml#L20)
https://travis-ci.org/github/Circuitscape/Circuitscape.jl/jobs/697038000

**Comment by vlandau** [comment]
So, we need to either allow AlgebraicMultigrid v0.2 or bump the Julia compat to 1.4.

**Comment by ViralBShah** [comment]
We should bump the Julia compat. Especially with all the threading omniscape uses, it is best to keep moving up with every release, since lots of issues keep getting fixed.

**Comment by ViralBShah** [comment]
Fixed in 21e5f61a3a63fa950828fca37df69d1dd1958eb3

**Comment by ViralBShah** [comment]
https://github.com/JuliaLinearAlgebra/AlgebraicMultigrid.jl/issues/65

**Comment by ViralBShah** [comment]
To make CI more reliable, we should revisit how many tests need to be run during CI.

**Comment by ranjanan** [comment]
To make CI pass we need to move to multi-threading. When that works, let's release 6.0. But till then we can make minor releases.

**Comment by ViralBShah** [comment]
Why do we need multi-threading to pass CI? Can we not make the CI test cases slightly less comprehensive for now?

**Comment by ViralBShah** [comment]
CI is still failing. We should get it to pass...

**Comment by vlandau** [comment]
Things seem to be passing now.
