### ISSUE TITLE
julia version and Circuitscape

### ISSUE THREAD

**Issue by hr881** [Circuitscape/Circuitscape.jl#251]
I don't have admin privileges at work, and in order to install julia my IT department needs to know if/how Circuitscape would be affected by updates for julia.  Will I need to update julia any time a new version is released in order to run Circuitscape?

**Comment by ViralBShah** [comment]
Julia and the Circuitscape package both can be installed in your user account without admin. In general, you won't need to update Julia to a new version every time - perhaps once a year.
