### ISSUE TITLE
effective resistance for one-to-all

### ISSUE THREAD

**Issue by angelabrennan** [Circuitscape/Circuitscape.jl#252]
Hi thanks so much for Circuitscape.jl and for all the time you put into answering users' questions. I am looking to use the one-to-all mode and in the Circuitscape documentation (McRae 2013) it looks like that mode should produce an output file with effective resistances between each node and ground. However, I only get this output file when I run the pairwise mode, not the one-to-all. Perhaps there is a way to specify this in the ini file that I am missing?

**Comment by ranjanan** [comment]
Hi Angela, thanks so much for your feedback. We're more than happy to help. As for getting resistances in the one to all mode, I believe we just return them to the user. So at the julia prompt, if you run: 
```julia
r = compute("some_problem.ini")
```
the variable `r` should have all the resistances you're looking for. I don't think we write them out, perhaps we should though. Let me check v4 to be sure, and create a PR if necessary. Also, if you'd like to get involved and submit a pull request (which should be a lot of fun!), I'm more than happy to guide you through it. :-)

**Comment by angelabrennan** [comment]
Thanks very much Ranjan! This worked perfectly!
Best,
Angela
