### ISSUE TITLE
Single precision issues?

### ISSUE THREAD

**Issue by glaroc** [Circuitscape/Circuitscape.jl#256]
Hi, with the most recent version of Circuitscape and Julia 1.4.1 and using tiff files as inputs and outputs, I'm getting bad results when using precision = single. This is a pair-to-pair approach with rasters defining the pairs. Everything works with precision = double, but current maps with single precision contain mostly zeros and are have only a few values around the edge. Is anyone else experiencing the same issue? I can supply example files if needed.

**Comment by ViralBShah** [comment]
Definitely supply the example files. Is the single precision valuable in general? Which solver is being used?

**Comment by glaroc** [comment]
What do you mean by "Is the single precision valuable in general" ? I'm using the default cg+amg

**Comment by glaroc** [comment]
Here are test files. 

https://www.dropbox.com/s/x060pn4ow6vhyxf/test_single_precision.zip?dl=0

**Comment by ViralBShah** [comment]
What I meant is - does single precision result in substantial enough savings in time or memory? If it is 10-20% or so, it may be best to remove the support - if it causes trouble. Assuming the problems are not too big, is it possible to try with cholmod? That might help understand where the issues might be.

@vlandau Would you be able to look into this?

**Comment by glaroc** [comment]
The time and memory (RAM) savings are in the order of 20-25%, so it's not a huge deal, but we do have to run this at least 10,000 times so it would make a difference in the end.

**Comment by ViralBShah** [comment]
Yes, those savings would add up. If it is an obvious bug of some kind, we should be lucky. This could be a deeper numerical solver thing, where the problem is ill-conditioned for Float32.

**Comment by ViralBShah** [comment]
FWIW, Julia now has 32-bit support for sparse Cholesky.
