### ISSUE TITLE
Denied access to folder

### ISSUE THREAD

**Issue by linhunt** [Circuitscape/Circuitscape.jl#261]
I have been trying to get the Julia version of Circuitscape to run. When I run Circuitscape it says the file directory was denied access. Are you able to run the Julia version of Circuitscape off of an external hard drive. The file path doesn't contain any spaces, special characters, or numbers. However, the node file does have numbers in the middle of the file name if that matters.

**Comment by vlandau** [comment]
If you are on Windows you may have to run Julia as administrator, or on Linux, `sudo julia`.

**Comment by ViralBShah** [comment]
It's not a Julia or a Circuitscape problem though.

**Comment by ranjanan** [comment]
@linhunt did Vincent's suggestion work for you?

**Comment by vlandau** [comment]
@linhunt hopefully you found a solution! I'm going to close this issue since we haven't heard back, but please feel free to reopen it if you continue to have problems.
