### ISSUE TITLE
"Error: syntax: invalid escape sequence"

### ISSUE THREAD

**Issue by BSiggery** [Circuitscape/Circuitscape.jl#271]
Hi all,

I appreciate this is probably something really straightforward to resolve but this is my first time working in Julia.
I have successfully installed Circuitscape in Julia 1.5.2 and ran the test successfully.

However, when I try to run it on an .ini file manually, I get the following: 
julia> compute("I:\DMU\Connectivity\BASELINE_RESULTS\_Oct19_Rerun\TBH\TBH6\Adder\Circuitresult\addercon2.ini")
ERROR: syntax: invalid escape sequence
Stacktrace:
 [1] top-level scope at none:1

I thought it may be due to me doing it on my own file that was perhaps incorrect, but I got the same error trying to manually run it on one of the test .ini files

julia> compute("C:\Users\BSiggery\.julia\packages\Circuitscape\oCGpr\test\input\network\mgNetworkVerify1.ini")
ERROR: syntax: invalid escape sequence
Stacktrace:
 [1] top-level scope at none:1

Could I get any suggestions? Thanks!

**Comment by ViralBShah** [comment]
Paste your ini file here. It is not formatted correctly, it seems.

**Comment by BSiggery** [comment]
Hi there, the mgNetworkVerify1.ini  should not have issues since it's the one in Julia's test files but I have pasted below anyway:
```

[Options for advanced mode]
ground_file_is_resistances = True
remove_src_or_gnd = keepall
ground_file = input/network/mgNetworkVerify1_grounds_resistances.txt
use_unit_currents = False
source_file = input/network/mgNetworkVerify1_sources.txt
use_direct_grounds = False

[Mask file]
mask_file = None
use_mask = False

[Calculation options]
low_memory_mode = False
parallelize = False
solver = cg+amg
print_timings = False
preemptive_memory_release = False
print_rusages = False
max_parallel = 0

[Short circuit regions (aka polygons)]
polygon_file = circuitscape/verify/1/polygons.asc
use_polygons = False

[Options for one-to-all and all-to-one modes]
use_variable_source_strengths = False
variable_source_file = None

[Output options]
set_null_currents_to_nodata = True
set_focal_node_currents_to_zero = False
set_null_voltages_to_nodata = True
compress_grids = False
write_cur_maps = True
write_volt_maps = True
output_file = output/mgNetworkVerify1.out
write_cum_cur_map_only = False
log_transform_maps = False
write_max_cur_maps = False

[Version]
version = 4.0.0-beta

[Options for reclassification of habitat data]
reclass_file = (Browse for file with reclassification data)
use_reclass_table = False

[Options for pairwise and one-to-all and all-to-one modes]
included_pairs_file = None
use_included_pairs = False
point_file = (Browse for file with locations of focal points or areas)

[Connection scheme for raster habitat data]
connect_using_avg_resistances = True
connect_four_neighbors_only = True

[Habitat raster or graph]
habitat_map_is_resistances = True
habitat_file = input/network/mgNetworkVerify1_graph_resistances.txt

[Circuitscape mode]
data_type = network
scenario = advanced

```

**Comment by BSiggery** [comment]
This is the code for my .ini generated with Circuitscape 4 GUI

```
[Options for advanced mode]
ground_file_is_resistances = True
remove_src_or_gnd = keepall
ground_file = (Browse for a ground point file)
use_unit_currents = False
source_file = (Browse for a current source file)
use_direct_grounds = False

[Mask file]
mask_file = (Browse for a raster mask file)
use_mask = False

[Calculation options]
low_memory_mode = False
parallelize = False
solver = cg+amg
print_timings = False
preemptive_memory_release = False
print_rusages = False
max_parallel = 0

[Short circuit regions (aka polygons)]
polygon_file = (Browse for a short-circuit region file)
use_polygons = False

[Options for one-to-all and all-to-one modes]
use_variable_source_strengths = False
variable_source_file = (Browse for a source strength file)

[Output options]
set_null_currents_to_nodata = False
set_focal_node_currents_to_zero = False
set_null_voltages_to_nodata = False
compress_grids = False
write_cur_maps = 1
write_volt_maps = 0
output_file = C:\Users\BSiggery\Desktop\RERUNS\TBH\TBH6\Adder\Circuitresult\addercon2.out
write_cum_cur_map_only = False
log_transform_maps = False
write_max_cur_maps = False

[Version]
version = 4.0.5

[Options for reclassification of habitat data]
reclass_file = (Browse for file with reclassification data)
use_reclass_table = False

[Logging Options]
log_level = INFO
log_file = C:\Users\BSiggery\Desktop\RERUNS\TBH\TBH6\Adder\Circuitresult\addercon2.log
profiler_log_file = None
screenprint_log = False

[Options for pairwise and one-to-all and all-to-one modes]
included_pairs_file = (Browse for a file with pairs to include or exclude)
use_included_pairs = False
point_file = C:\Users\BSiggery\Desktop\RERUNS\TBH\TBH6\Adder\ASCII\core2.txt

[Connection scheme for raster habitat data]
connect_using_avg_resistances = True
connect_four_neighbors_only = True

[Habitat raster or graph]
habitat_map_is_resistances = True
habitat_file = C:\Users\BSiggery\Desktop\RERUNS\TBH\TBH6\Adder\ASCII\resist.txt

[Circuitscape mode]
data_type = raster
scenario = pairwise
```

**Comment by ranjanan** [comment]
Can you run `compute(raw"I:\DMU\Connectivity\BASELINE_RESULTS_Oct19_Rerun\TBH\TBH6\Adder\Circuitresult\addercon2.ini")`?

**Comment by BSiggery** [comment]
> Can you try `compute(raw"I:\DMU\Connectivity\BASELINE_RESULTS_Oct19_Rerun\TBH\TBH6\Adder\Circuitresult\addercon2.ini")`?

Yes! That helps. Now I get a new error: "ERROR: SystemError: opening file "output/mgNetworkVerify1.out": No such file or directory"

Could you explain how to create an .out file? If it just a blank notepad doc?

Could you also explain why I need to use the "raw" command?

**Comment by ranjanan** [comment]
Re creating out files: You don't need to create one yourself. Circuitscape will just create one for you. Just specify an absolute path like you have in `addercon2.ini`. 

Re the raw syntax: 
```julia
julia> raw"I:\DMU\Connectivity\BASELINE_RESULTS_Oct19_Rerun\TBH\TBH6\Adder\Circuitresult\addercon2.ini"
"I:\\DMU\\Connectivity\\BASELINE_RESULTS_Oct19_Rerun\\TBH\\TBH6\\Adder\\Circuitresult\\addercon2.ini"
```
You need two escape characters while specifying strings in the julia prompt in Windows. Tab-complete will automatically do that for you. If you're pasting from your explorer window, the `raw` command is an easy way to do the escaping for you. :-) 
 
Error when running the test file: You need to be in the test folder of the package (pwd() == "path\\to\\test\\folder") for that path to make sense to julia. Julia is looking for a folder called output in `pwd` and it can't find it. 

Try running your original problem with the INI you pasted, and let me know how to goes. (Open a text file in that directory, paste the contents into it and call it `addercon2.ini`. Now run `compute("path\\to\\ini\\file")`)

**Comment by BSiggery** [comment]
Hi Ranjanan, thanks a lot for your reply! It looks like it's working fine now with the raw command.

I'm not sure exactly what you mean about pwd? But I suppose it doesn't matter since the more important thing is that I've managed to run my own file. 

One last question, do generate the .ini files from the Circuitscape 4 GUI I have to "run" the problem but then can just cancel it straight away? Will it keep the .ini it generated?

**Comment by vlandau** [comment]
@BSiggery I'm not sure if the ini file is written and will be saved if you cancel the job from v4. Did you find out? I'm going to close this issue since the original problem was resolved, but if problems persist, feel free to respond here or reach out on the [gitter page](https://gitter.im/Circuitscape/Circuitscape.jl). cc @ranjanan
