### ISSUE TITLE
ValueError: could not broadcast input array fro, shape (3,1) into shape (3)

### ISSUE THREAD

**Issue by RachLamb** [Circuitscape/Circuitscape.jl#272]
Error running Pinchpoint Mapper in Linkage Mapper Toolkit using ArcGIS 10.6. Had to use Circuitscape v4.0 to get the script to run. Does this value suggest an underlying error with the original linkage map?

[valueerror.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5585165/valueerror.txt)

**Comment by vlandau** [comment]
@RachLamb sorry for the delay in getting back to you. Unfortunately, Circuitscape v4 is no longer actively supported. However, you may have better luck posting an issue in the [Linkage Mapper repo](https://github.com/linkagescape/linkage-mapper/issues).
