### ISSUE TITLE
ERROR: KeyError: key "Zlib_jll" not found

### ISSUE THREAD

**Issue by tildigg** [Circuitscape/Circuitscape.jl#274]
I am trying to download circuit scape. I have downloaded Julia and followed the code to install circuit scape but i keep getting this message.

**Comment by vlandau** [comment]
@tildigg sorry for the delay in getting back to you. Can you please post the full stacktrace in a code black, as well as information about your operating system and which version of Julia you're using?

**Comment by ViralBShah** [comment]
Did you install using the Julia package manager?
