### ISSUE TITLE
Include pairs not implemented in the polygon focal point case

### ISSUE THREAD

**Issue by ranjanan** [Circuitscape/Circuitscape.jl#278]
When the point file contains polygons, include pairs does not seem to be called anywhere.

**Comment by vlandau** [comment]
[Here](https://drive.google.com/drive/folders/1ohzhMcFV6YALXnnZ_tMBbT0OZ4Oj05Wn?usp=sharing) are the files to reproduce.

**Comment by ranjanan** [comment]
Fixed by #374
