### ISSUE TITLE
ERROR: ArgumentError: column indices J[k] must satisfy 1<= J[k]  <= n

### ISSUE THREAD

**Issue by cottetro** [Circuitscape/Circuitscape.jl#281]
Hi,
When trying to run Circuitscape from the command line in Julia, I get the following error:

ERROR: ArgumentError: column indices J[k] must satisfy 1<= J[k]  <= n
(See also the full traceback in the files attached)

I can run this same data through the Circuitscape.py version from the GUI and from R. I was also able to run the Circuitscape test from the package and even launch some of them manually from the command line.  I am a new to Julia and don't really know what the problem is here.

Furthermore, I switched from the .py  version to the .jl version trying to avoid this issue: [https://github.com/Circuitscape/Circuitscape.py/issues/77] , thus the "Pairs_to_include" file. Sadly I could not find the comment mentioned in the aforementioned issue.

Solving any of those two issues would have me unstuck. 

Julia: 1.0.5
Circuitscape: 5.5.5
Windows 10

Thanks for your help

[Test9.zip](https://github.com/Circuitscape/Circuitscape.jl/files/5967259/Test9.zip)

**Comment by vlandau** [comment]
No there shouldn't be. Maybe we just do a simple error throw if the nodes aren't ordered correctly?

**Comment by ranjanan** [comment]
Yep, I agree. Let's throw the error. Same with the complaint about nodes being marked from 1 instead of 0.
