### ISSUE TITLE
Issue branch_current output in network mode

### ISSUE THREAD

**Issue by mvszuri** [Circuitscape/Circuitscape.jl#282]
Hello Circuitscape-team,

I am running Circuitscape 5 on a network in advanced mode. As far as I understand, the branch_currents output file should show the current in each of the edges of the network. The calculations seem to be running fine, but I have encountered an issue with this branch_current file. If I run Circuitscape on the following example files:

[mgNetworkVerify3_graph_resistances.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967891/mgNetworkVerify3_graph_resistances.txt)
[mgNetworkVerify3_grounds_resistances.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967892/mgNetworkVerify3_grounds_resistances.txt)
[mgNetworkVerify3_sources.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967893/mgNetworkVerify3_sources.txt)
With the following settings:
[github_test.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967899/github_test.txt)

The output ...branch_currents.txt file has an entry for every edge in the network, but the edge IDs are not the same as in the input graph file:
1.0	2.0	9.786794575879977
2.0	3.0	5.221873918061166
2.0	4.0	5.221873918061166
3.0	5.0	6.098668493941138
4.0	5.0	6.098668493941138

There seems to be a 1 added to each edge ID. This would be an easy fix, but if I run Circuitscape on my own larger network:

[resistance.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967921/resistance.txt)
[ground.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967924/ground.txt)
[sources.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967925/sources.txt)
with the following settings:
[test_run2.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967930/test_run2.txt)

The ...branch_currents.txt file not only contains less rows (i.e. pairs) than the input resistance file, the edge IDs have been mixed up considerably:
[test_run2_branch_currents.txt](https://github.com/Circuitscape/Circuitscape.jl/files/5967934/test_run2_branch_currents.txt)

I would very much appreciate your help solving this issue. Thanks in advance!

Best regards,
Maarten van Strien

**Comment by ranjanan** [comment]
Hi Maarten, 

Thanks for submitting this issue. Could you mention which version of Circuitscape you're on?

```julia
]st
```
should tell you.

**Comment by mvszuri** [comment]
I'm using Circuitscape v5.7.1. Thanks for addressing this issue.

**Comment by mvszuri** [comment]
I have performed some more experiments with the branch_currents output of Circuitscape 5. I have found that if you subtract 1 from the node IDs in the ...branch_currents.txt files, the original node IDs are reproduced (the order of the edges may be different to the input file). Furthermore, I have compared the input network to the output network, which I reconstructed from the ....branch_currents.txt file. Below is the input network in blue and the output network in red. As can be seen, several dangling edges were removed from the input networks. This is the reason that my output branch_currents file has fewer edges than the input.
![Difference_input_output](https://user-images.githubusercontent.com/37740095/109147520-641daa00-7765-11eb-8cd9-14284f1e3fee.jpg)

Instead of removing these dangling edges from the network, it may be good to include them and give them a current of 0.

**Comment by venkanna37** [comment]
I am also facing the same issue, namely:

1. IDs in branch and node currents filename not same as input files, instead it is adding one to the pair IDs (eg: Circuitscape_network_branch_currents_2_3.txt instead of Circuitscape_network_branch_currents_1_2.txt)
2. The final resistance.out and resistance_3column.out files from Circuitscape 5 (v5.8.1; Julia 1.6.1.) have repeating node IDs and resistance values as against the .out files from Circuitscape 4.

Example outputs: 
[output_resistances.txt](https://github.com/Circuitscape/Circuitscape.jl/files/6770172/output_resistances.txt)
[output_resistances_three_columns.txt](https://github.com/Circuitscape/Circuitscape.jl/files/6770173/output_resistances_three_columns.txt)

Tagging @indranil-wii

**Comment by ranjanan** [comment]
@mvszuri and @venkanna37 choosing to start counting nodes from 0 or 1 is just a choice of convention. Circuitscape.jl chooses to count from 1. You can definitely feed it inputs that start counting nodes from 0. We handle that, but with #324, we will specifically log that we start counting from 1 and you should expect to see that in the outputs.

**Comment by ranjanan** [comment]
@venkanna37 please check if this issue persists when with the latest Circuitscape, which will be tagged after #324 is merged.

**Comment by ranjanan** [comment]
Closing this for now. Please reopen if there's an issue.
