### ISSUE TITLE
Cumulative current map all NODATA in circuitscape.jl, but show currents in circuitscape GUI

### ISSUE THREAD

**Issue by ilonamihalik** [Circuitscape/Circuitscape.jl#289]
Hi all

I'm relatively new to Circuitescape but have been having issues with my cumulative maps using .jl. I'm running Circuitscape on raster data and in pairwise mode. I have 97 focal nodes in my study area.

Running my resistance and nodes layers in Circuitscape.jl, each iteration map shows pairwise connections, but my cumulative map shows all as "NODATA". 

Running the **same** layers using the Circuitscape GUI works though, and my cumulative map shows connections. 

I've re-updated Julia on my computer and everything. It's worked for me in the past with other layers (late 2020) which is strange.

Any thoughts?

With thanks.

**Comment by ranjanan** [comment]
Could you please upload your files in a dropbox / google drive and paste the link? I can take a look.

**Comment by ilonamihalik** [comment]
Thanks very much Ranjan. Here is a dropbox link: https://www.dropbox.com/sh/wmcx4up6el3xz4c/AAB3faW1gw-KVgDIIeaN1HdOa?dl=0

Please let me know if you need any more info.

Best,
Ilona

**Comment by vlandau** [comment]
Hi @ilonamihalik, apologies for the delay in getting back to you here. Have you resolved the issue? If not I can take a look at your inputs to see if I can reproduce the issue.

**Comment by ilonamihalik** [comment]
Thanks @vlandau. It hasn't been resolved yet. For now I've been running a smaller area using the Circuitscape GUI which has been working. Ideally I'd like to be able to run the larger area in Julia. 

Let me know if there's any more info I can provide.

Ilona

**Comment by ilonamihalik** [comment]
Hi @vlandau and @ranjanan - I just wanted to update that I was able to resolve this issue. I was missing a line in my .ini file and it now runs with no problem. thank you for looking into this!
