### ISSUE TITLE
memory error

### ISSUE THREAD

**Issue by ModiShrushti** [Circuitscape/Circuitscape.jl#292]
I am using circuitscape toolbox in ArcGIs and getting the error
cs_arc.py failed. Details follow
Python error on line 236 of cs_arc.py version 2013-05-29 memory error
Failed to execute circuitscape.
How to solve this issue

**Comment by ranjanan** [comment]
I'm afraid that that version of the ArcGIS toolbox is currently deprecated. Could you export your maps and just run Circuitscape on it?

**Comment by ModiShrushti** [comment]
I have tried to run Circuitscape 4 (GUI version) but it is not responding after few seconds running the program. Also I tried to run Circuitscape 5 using julia but again I am not well acquainted with it and could not follow the instruction
julia> compute("path/to/config/file.ini")

**Comment by ranjanan** [comment]
Circuitscape works by taking in an "INI file" which is a set of options and paths (look at the [tests](https://github.com/Circuitscape/Circuitscape.jl/tree/master/test)). One way to generate it to use [INIBuilder (check docs)](https://docs.circuitscape.org/Circuitscape.jl/latest/#Building-a-Circuitscape-Job). Alternatively, you can simply copy and paste one of those test files and change the paths and the options you want to use.

**Comment by ranjanan** [comment]
Feel free to post questions here. I'm happy to guide you through the process. Once we figure it out, I'm happy to add any documentation you think is useful for this use case.

**Comment by ModiShrushti** [comment]
Hi,
I was able to successfully run Circuitscape julia and I was using the same
resistance file for optimisation in ResistanceGA. After fixing everything I
realised that I am getting the opposite results from what has been
expected. I am getting higher resistance for favourable habitat and
vice-versa based on the ecology of my species. After some reading I
realised the issue can be with the resistance surface . This is the
sequence which I used for generation of input resistance surface for
Circuitscape. Please correct me if I am wrong.

1. Convert all the files into raster format
2. Reclassify the categories using *reclassify tool in ArcGIS*
3. Make all the resistance surface with similar resolution and convert into
.asc format using "*export to circuitscape"* tool in ArcGIS
4. Use *Gnarly toolbox* for final input and adding the resistance and
habitat quality value for each category



Thanks
Shrushti

Shrushti Modi
Ph.D. Scholar,
Dept. of Animal Ecology and Conservation Biology,
Wildlife Institute of India,
Dehradun
Ph: +917088383245
Email Address: ***@***.***, ***@***.***

**Comment by ranjanan** [comment]
Could you check whether your resistance file is regarded as resistances or conductances? 

 

In your INI file, there should be an option like the following: https://github.com/Circuitscape/Circuitscape.jl/blob/master/test/input/raster/pairwise/1/sgVerify1.ini#L40

 

Basically, if the resistance file you’re feeding Circuitscape contains resistances, that flag should be true. And false if it’s conductances.

**Comment by ModiShrushti** [comment]
I have rechecked it is regarded as resistance file only.

**Comment by ranjanan** [comment]
I see, would you mind attaching your inputs in a google drive file? I’ll take a look.

**Comment by ModiShrushti** [comment]
Sure. Please find attached the .asc files, I have used for the analysis. I
have used two different sets one with considering the resistance value
during reclassification and second using reclassification without
resistance values.



Thanks
Shrushti


Shrushti Modi
Ph.D. Scholar,
Dept. of Animal Ecology and Conservation Biology,
Wildlife Institute of India,
Dehradun
Ph: +917088383245
Email Address: ***@***.***, ***@***.***

**Comment by ranjanan** [comment]
Hey Shrushti,

I can't see the attachments. You're going to have to either attach them on Github or send a google drive link. Please be sure to include all your INI, focal points files, reclass table, and other things. If you did the reclassification in Circuitscape itself, you may be running into https://github.com/Circuitscape/Circuitscape.jl/issues/231

**Comment by ModiShrushti** [comment]
I have gnarly tool for final file. I am attaching all of them here.
 inputvariable_r_sum.asc
<https://drive.google.com/file/d/1q-crCniyt-7ToOJVGudWNZaWWm3XgDUT/view?usp=drive_web>

 poptignode2.asc
<https://drive.google.com/file/d/1Jh752P9nfEh7SKSZ8gRNLo6s2atFIYQE/view?usp=drive_web>

 sumtest
<https://drive.google.com/file/d/1tdODxfi90L7ATfzjyEy2YNbCzoDgQ0PM/view?usp=drive_web>

Shrushti Modi
Ph.D. Scholar,
Dept. of Animal Ecology and Conservation Biology,
Wildlife Institute of India,
Dehradun
Ph: +917088383245
Email Address: ***@***.***, ***@***.***

**Comment by ranjanan** [comment]
@ModiShrushti I get "AccessDenied" on your files. Could you enable access to them?

**Comment by ranjanan** [comment]
Closing this for now. Please reopen if there's an issue
