### ISSUE TITLE
Circuitscape 5 is not writing cumulative branch and node current files for network mode

### ISSUE THREAD

**Issue by venkanna37** [Circuitscape/Circuitscape.jl#303]
Circuitscape 5 is not writing cumulative currents files when I run with the network data type. While the same settings (.ini and habitat files) are working fine with Circuitscape 4 and are giving the desired cumulative branch and node currents files.

I am running Circuitscape 5 (v5.8.1) in Julia v1.6.1 with the following .ini and network data:
[Circuitscape_graph2.txt](https://github.com/Circuitscape/Circuitscape.jl/files/6769271/Circuitscape_graph2.txt)
[Circuitscape_network_ini.txt](https://github.com/Circuitscape/Circuitscape.jl/files/6769276/Circuitscape_network_ini.txt)

Tagging @indranil-wii

**Comment by vlandau** [comment]
Hi @venkanna37, apologies for such a late response to this issue. I think this must be because you are providing the same file as both your point file and your habitat map. For network and raster data in pariwise mode, you need to supply a separate file that specifies the points (nodes) that you want to connect.

From [the docs](https://docs.circuitscape.org/Circuitscape.jl/latest/usage/#Illustrations-of-analyses-with-network-data):
>For pairwise analysis we would also supply a list of focal nodes (containing at least two node numbers, but as many as...the number of nodes in the circuit) between which we want to perform calculations.

**Comment by venkanna37** [comment]
Hello @vlandau , thank you for the reply and apologies the for late response. After modifying the point file, the branch and node current files are improved, the resistance column are not being considered as nodes (before modification, resistances were considered as nodes in output). Still, Circuitescape5 is not writing cumulative node and branch currents files. I am attaching my .ini, point and resistance files,  can you please check when you find the time and let me know if I have to make any modification in them.

Thank you.

[Circuitscape_network_ini.txt](https://github.com/Circuitscape/Circuitscape.jl/files/7177784/Circuitscape_network_ini.txt)
[centrality_points.txt](https://github.com/Circuitscape/Circuitscape.jl/files/7177787/centrality_points.txt)
[centrality_resistances.txt](https://github.com/Circuitscape/Circuitscape.jl/files/7177789/centrality_resistances.txt)

**Comment by vlandau** [comment]
Unfortunately for network mode I think the cumulative branch currents are currently not able to be written, see #119. cc @ranjanan

**Comment by venkanna37** [comment]
Thank you for confirmation @vlandau. It will be very useful if Circuitescape-5 can write cumulative branch and node current files.

**Comment by ranjanan** [comment]
Closed by https://github.com/Circuitscape/Circuitscape.jl/pull/318

**Comment by ranjanan** [comment]
@venkanna37 and @johngallo this should now work with version 5.9.1

**Comment by venkanna37** [comment]
Thank you so much @ranjanan  I will try it
