### ISSUE TITLE
What wrong by "output/mgNetworkVerify1.out"

### ISSUE THREAD

**Issue by ammonite** [Circuitscape/Circuitscape.jl#307]
Sorry. It is my first trying on Circuitscape:
julia> compute(".julia/packages/Circuitscape/Qr6wW/test/input/network/mgNetworkVerify1.ini")
ERROR: SystemError: opening file "output/mgNetworkVerify1.out": No such file or directory
......
[10] compute(path::String)
    @ Circuitscape ~/.julia/packages/Circuitscape/Qr6wW/src/run.jl:17

Julia 1.6.1
Thank you very much!

**Comment by vlandau** [comment]
Hi @ammonite is this happening when you run `Pkg.test("Circuitscape")`?

**Comment by ammonite** [comment]
Hi @vlandau thanks a lot. 
---
Test Summary:          | Pass  Total
Double Precision Tests |  662    662
     Testing Circuitscape tests passed 
---
and always get similar error like this by start() function ---- no some files or directories.

**Comment by vlandau** [comment]
Can you please post the full output from the Julia terminal when you run `start()`? This will help us to debug.

**Comment by ranjanan** [comment]
@ammonite ` compute(".julia/packages/Circuitscape/Qr6wW/test/input/network/mgNetworkVerify1.ini")` would work only if your current directory is the home directory. On windows that isn't the case if you've just opened up Julia.

**Comment by ammonite** [comment]
Thank you very much.@vlandau, @ranjanan, it work, cd to correct directory.

**Comment by ranjanan** [comment]
Thank you for confirming @ammonite, I'll close this then.
