### ISSUE TITLE
Empty output file

### ISSUE THREAD

**Issue by Mavisan6** [Circuitscape/Circuitscape.jl#327]
I have been trying to run a few experiments on circuitscape but the resulting current maps are made of a grid where every cell is zero. Once the experiment it's finished however the console is showing me a grid with numbers. I was wondering whether those numbers were the ones that the output file was supposed to contain. 

Here is a folder with the ini file, the focal nodes and resistance map as well as the resulting output map. 

https://drive.google.com/drive/folders/1ln5QgznqwC88jvxmOiVWePN_s1M0H3V9?usp=sharing

**Comment by merijnvdb** [comment]
Hi @vlandau , while my issue is similar I do not think it is a duplicate;
it seems like @Mavisan6 does get output files, but they are not what they should be.

My problem is that no cumulative current map is written at all, despite the tool seeming to run without trouble.

Some details on my input below, I will also attach the node raster file and resistance raster.
[Uploading circuit.zip…]()

Modeling mode: pairwise
Resistance raster: see attached
Focal node raster: see attached
output file path: a path only one link away from my C-drive (C::folder::subfolder::basefilename)
Write current maps: unchecked
Mapping options: CHECK write cumulative current map only

The rest is left untouched.

Then the process will start...;
Graph has 3462333 nodes, 434 focal nodes and 82 components.
Solving focal pair 1 of 204 ( _slightly strange, I would expect 434/2 pairs?_)
It will finish successfully, but without any current map to be found in my destination folder.

Detail: if I run everything the same, but CHECK 'write current maps' (regardless of whether write cumulative current map only is checked),
everything seems the same except the process will start with 'Solving focal pair 1 of 20506', so I've never let this process finish of course, it would take ages.

P.S: When importing the resistance raster it may show min-max different from 1-100, I use 'set raster properties' to change the min and max values to 1 - 100 before using it in Circuitscape.

**Comment by ranjanan** [comment]
Thanks for posting this. I'll take a look.

**Comment by ranjanan** [comment]
This should have been picked out by our tests. #330 should fix this, and add a test

**Comment by ranjanan** [comment]
Fixed by #330

**Comment by ranjanan** [comment]
@merijnvdb and @Mavisan6 I've fixed this and tagged a new version. Feel free to reopen if it doesn't work.

**Comment by merijnvdb** [comment]
Thank you @ranjanan , I'm quite new to Github so I'm not sure where to find the proposed solution? Is it a debugged version of the toolbox, or an output file or something? I can see a lot of coding in #330, but am not sure how to apply this in my arcmap toolbox?
