### ISSUE TITLE
Error: MethodError: no methjod matching connected_components

### ISSUE THREAD

**Issue by ClarkNH** [Circuitscape/Circuitscape.jl#335]
Hello,

I am trying to run an .ini file in Julia Circuitscape. When I run it in Julia 1.6.3 with Circuitscape 5.8.4 I get the following error:

```julia
julia> compute("D:/GIS_Data/mclark/hawaii/climate_flow/w2w3/n2s/ns1i1.ini")
[ Info: 2021-11-18 12:08:41 : Precision used: Double
[ Info: 2021-11-18 12:08:51 : Reading maps
[ Info: 2021-11-18 12:12:35 : Resistance/Conductance map has 78854400 nodes
ERROR: MethodError: no method matching connected_components(::SimpleWeightedGrap
hs.SimpleWeightedGraph{Int64, Float64})
Closest candidates are:
  connected_components(::LightGraphs.AbstractGraph{T}) where T at D:\Users\melis
sa_clark\.julia\packages\LightGraphs\IgJif\src\connectivity.jl:100
Stacktrace:
 [1] compute_advanced_data(data::Circuitscape.RasterData{Float64, Int64}, flags:
:Circuitscape.RasterFlags, cfg::Dict{String, String})
   @ Circuitscape D:\Users\melissa_clark\.julia\packages\Circuitscape\DtnvC\src\
raster\advanced.jl:59
 [2] raster_advanced(T::Type, V::Type, cfg::Dict{String, String})
   @ Circuitscape D:\Users\melissa_clark\.julia\packages\Circuitscape\DtnvC\src\
raster\advanced.jl:27
 [3] _compute(T::Type, V::Type, cfg::Dict{String, String})
   @ Circuitscape D:\Users\melissa_clark\.julia\packages\Circuitscape\DtnvC\src\
run.jl:45
 [4] macro expansion
   @ .\timing.jl:287 [inlined]
 [5] compute(path::String)
   @ Circuitscape D:\Users\melissa_clark\.julia\packages\Circuitscape\DtnvC\src\
run.jl:31
 [6] top-level scope
   @ REPL[8]:1
```

I can run the same .ini in an older version of Julia (1.4.0)

Here is the link to the data: https://tnc.box.com/s/9lkjvgkzie77r85r0un73ktw6sidfdkt

Thank you for your help!
Melissa

**Comment by vlandau** [comment]
Hi Melissa! I think this _might_ be fixable by updating to Circuitscape 5.10. Would you mind updating and seeing it that fixes it? If not, we can go ahead and work on reproducing the problem on our end to find out what's going on.

**Comment by ClarkNH** [comment]
Good Suggestion. I just updated it, but unfortunately I still get the same error.

**Comment by vlandau** [comment]
Can you post the version of SimpleWeightedGraphs that you're using? You can get this with `using Pkg; Pks.status("SimpleWeightedGraphs")`. If it is not at version 1.2, then you may need to update it to solve this problem.

There were some changes to the graphs packages, and Circuitscape now requires the latest version of each. That being said, it looks like we're not explicitly enforcing those version requirements, so I will add them.

**Comment by ClarkNH** [comment]
I doesn't look like I have "SimpleWeightedGraphs". I'll add it right now and see if it helps the problem.

**Comment by vlandau** [comment]
I have issued a new patch release for Circuitscape (v5.10.1) that should resolve the versioning issues for SimpleWeighteGraphs and hopefully resolve this issue. It should be available in less than 15 minutes.
