### ISSUE TITLE
ERROR: LoadError: On worker 2:

### ISSUE THREAD

**Issue by joncjones** [Circuitscape/Circuitscape.jl#340]
Hi guys - I am getting the attached errors (see error.txt and output.txt below) when running the dev version of Circuitscape with Julia 1.6.2. 

Any thoughts on how to address this ? Thanks !

For info I switched to using the dev version because when I tried using the stable version I was getting the same error I see listed in Issues [ERROR: MethodError: no method matching Connected_components(::SimpleWeightedGraphs.SimpleWeightedGraph{Int64, Float64})]

All the best 

Jonathan 

[error.txt](https://github.com/Circuitscape/Circuitscape.jl/files/7692265/error.txt)
[output.txt](https://github.com/Circuitscape/Circuitscape.jl/files/7692266/output.txt)

**Comment by ranjanan** [comment]
@joncjones I believe this was fixed in #325. Closing this for now, but please check with the latest Circuitscape and feel free to reopen
