### ISSUE TITLE
Short circuit regions not recognized

### ISSUE THREAD

**Issue by wpeterman** [Circuitscape/Circuitscape.jl#353]
I've been trying to implement a pairwise analysis with short circuit regions/polygons with Circuitscape v5.11.1. Circuitscape runs, but does not use the short circuit regions. When the same .ini file is run with v4.0.5, it correctly runs. 

Data and .ini file to reproduce are attached.
[region_error.zip](https://github.com/Circuitscape/Circuitscape.jl/files/8255276/region_error.zip)

**Comment by ranjanan** [comment]
Still an issue it seems? looking into it.

**Comment by ranjanan** [comment]
Yeahhhh this is so dumb but what was happening was Circuitscape expected "True" or "true" or "1" but didn't recognize "TRUE". It works when I changed it to one of those values.
