### ISSUE TITLE
Error issue question

### ISSUE THREAD

**Issue by LycanSquatch** [Circuitscape/Circuitscape.jl#356]
### Discussed in https://github.com/Circuitscape/Circuitscape.jl/discussions/355

<div type='discussions-op-text'>

<sup>Originally posted by **LycanSquatch** March 29, 2022</sup>
So I have a question about an error. I'm not sure what's causing this problem the layers or files I'm using work on the stand alone program Circuitscape 4.0. But it takes about a month for each run which is why I was trying to expedite this process by using this new version. I keep getting this error while trying to run Circuitscape through Julia.  Error: GDALError (CE_Failure, code 10): Pointer 'hDS' is NULL in 'GDALGetRasterBand'. Any Ideas on how to solve this issue would be much appreciated. </div>

**Comment by vlandau** [comment]
Hi @LycanSquatch, thanks for your questions. This looks similar to another issue in Omniscape.jl (https://github.com/Circuitscape/Omniscape.jl/issues/85) that didn't have a clear solution (it seemed to be an issue with the version of Julia they were using).

Can you confirm which version of Circuitscape you are using, as well as your Julia version? The get the version of Circuitscape, run `using Pkg; Pkg.status("Circuitscape")` in the terminal.

**Comment by LycanSquatch** [comment]
Hi @vlandau, thanks for the quick response I'm using Julia Version 1.7.0 (2021-11-30), and Circuitscape v5.10.2.

**Comment by vlandau** [comment]
Okay thanks! As a first step, can you see if upgrading to Circuitscape 5.11.1 resolves the issue? It may not, but from a debugging perspective it will be good to work from the latest version anyway.

**Comment by vlandau** [comment]
And if you have access to the INI file that INI builder is creating, that would be helpful as well.

**Comment by LycanSquatch** [comment]
I resolved the issue, it was a problem with my file. Thanks for your help!
