### ISSUE TITLE
Error happens in Julia. "At least one focal node location falls outside of habitat map"

### ISSUE THREAD

**Issue by lu-vits** [Circuitscape/Circuitscape.jl#360]
Hi guys,
I'm trying to run circuitscape through julia, but the error is returned
"At least one focal node location falls outside of habitat map"
Can you explain to me why this happens?

**Comment by SamLS84** [comment]
I'm having this same issue but none of my focal nodes are outside my habitat map so can anyone tell me what I need to do to fix this?  I'm not great with circuitscape and have been battling it for over 6 months and keep getting one issue after another.  Any help will be greatly appreciated.
