### ISSUE TITLE
Advanced run not completing (see also #131)

### ISSUE THREAD

**Issue by SimonTapper** [Circuitscape/Circuitscape.jl#369]
I am trying to run Circuitscape in advanced mode (wall-to-wall), but the run never completes. It calculates the 'Time taken to solve the linear system' and then continues to process indefinitely (as far as I can tell). I have tried several versions of Julia (1.6.0, 1.6.3, 1.67, 1.72, 1.8), and it's the same situation in all of them. I have tried changing some aspects of the ini file (below), but have not succeeded. For example, I have tried with solver = cg+amg, with different ground and source asc files, and with different/additional arguments (e.g., write_cur_maps = 1). 
```julia
[circuitscape options]
data_type = raster
scenario = advanced
ground_file_is_resistances = True
source_file = path to source.asc
ground_file = path to ground.asc
output_file = path to out.out
habitat_file = path to habitat file.asc
solver = cholmod
print_timings = True
write_cur_maps = True
connect_four_neighbors_only = False
connect_using_avg_resistances = True
habitat_map_is_resistances = True
```

I would be willing to share my data privately if requested. 

Circuitscape version v5.11.2, obtained from running 'using Pkg; Pkg.status("Circuitscape")', with Julia versions 1.6, obtained from versioninfo().

**Comment by ranjanan** [comment]
Hi @SimonTapper, could you please share these files with me please? Also, when it gets stuck at the Julia prompt, could you hit Control+C? This will interrupt the process and we can see where it is getting stuck.

**Comment by ranjanan** [comment]
Have you also tried with `solver = cg+amg`?

**Comment by ranjanan** [comment]
Yes, could you please post that error message here?

**Comment by ranjanan** [comment]
All of the directions run for me with this PR. Let me make another release and ask you to update to the latest release and check.

**Comment by ranjanan** [comment]
Once this https://github.com/JuliaRegistries/General/pull/74737 merges, please update Circuitscape to 5.12.1 and then try again.
