### ISSUE TITLE
Error during Pkg.test("Circuitscape")

### ISSUE THREAD

**Issue by harshadkarandikar** [Circuitscape/Circuitscape.jl#377]
Hi,

I am trying to install Circuitscape on a M1 Mac Studio with Julia 1.8.5. While the installation goes smoothly, Pkg.test("Circuitscape") throws up errors. I tried running a job that runs on another M1 Mac (in case there was just an issue with testing), but it did not work.

```Julia
Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading.
     Testing Running tests...
WARNING: method definition for multiple_solver at /Users/abcd/.julia/packages/Circuitscape/HNOrX/src/raster/advanced.jl:275 declares type variable S but does not use it.
WARNING: could not import Circuitscape.compute_mklpardiso into Main
pwd = /Users/abcd/.julia/packages/Circuitscape/HNOrX/test
Test Summary: | Pass  Total  Time
Unit tests    |   16     16  7.5s
┌ Warning: 2023-02-03 14:24:03 : CHOLMOD only works with double precision. Converting single precision matrix to double
└ @ Circuitscape ~/.julia/packages/Circuitscape/HNOrX/src/logging.jl:25

signal (10): Bus error: 10
in expression starting at /Users/abcd/.julia/packages/Circuitscape/HNOrX/test/runtests.jl:15
unknown function (ip: 0x120b78b04)
Allocations: 145519460 (Pool: 145435731; Big: 83729); GC: 110
ERROR: Package Circuitscape errored during testing (received signal: 10)
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Types.jl:67
  [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
    @ Pkg.Operations /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/Operations.jl:1813
  [3] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:434
  [4] test(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:156
  [5] test(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:145
  [6] #test#87
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:144 [inlined]
  [7] test
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:144 [inlined]
  [8] #test#86
    @ /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:143 [inlined]
  [9] test(pkg::String)
    @ Pkg.API /Applications/Julia-1.8.app/Contents/Resources/julia/share/julia/stdlib/v1.8/Pkg/src/API.jl:143
 [10] top-level scope
    @ REPL[5]:1
```

**Circuitscape and Julia version** 
Circuitscape v5.12.2 (obtained from running `using Pkg; Pkg.status()` and Julia v1.8.5 (obtained from running `versioninfo()`)

Am I missing anything? Thank you!

**Comment by harshadkarandikar** [comment]
Hello,

I still haven't been able to resolve this issue. Any ideas on what I could possibly try to get Circuitscape running? Thank you!

**Comment by nataliemyers12** [comment]
I am also having this error and would love any insight available

**Comment by ViralBShah** [comment]
Try the latest Circuitscape master and see if it helps. It works fine on my M2.

**Comment by knussear** [comment]
I'm also getting a stacktrace error after a fresh install of julia and circuitscape

I'm on Ubuntu 22.04

julia> using Pkg; Pkg.status()
Status `~/.julia/environments/v1.9/Project.toml`
  [2b7a1792] Circuitscape v5.12.3
  [fd094767] Suppressor v0.2.4

Pkg.test("Circuitscape")

in expression starting at /home/knussear/.julia/packages/Circuitscape/33lUW/test/runtests.jl:1
ERROR: Package Circuitscape errored during testing
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types /usr/share/julia/stdlib/v1.9/Pkg/src/Types.jl:69
  [2] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, julia_args::Cmd, test_args::Cmd, test_fn::Nothing, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool)
    @ Pkg.Operations /usr/share/julia/stdlib/v1.9/Pkg/src/Operations.jl:2026
  [3] test
    @ /usr/share/julia/stdlib/v1.9/Pkg/src/Operations.jl:1907 [inlined]
  [4] test(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; coverage::Bool, test_fn::Nothing, julia_args::Cmd, test_args::Cmd, force_latest_compatible_version::Bool, allow_earlier_backwards_compatible_versions::Bool, allow_reresolve::Bool, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:441
  [5] test(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:156
  [6] test(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:145
  [7] #test#75
    @ /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:144 [inlined]
  [8] test
    @ /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:144 [inlined]
  [9] #test#74
    @ /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:143 [inlined]
 [10] test(pkg::String)
    @ Pkg.API /usr/share/julia/stdlib/v1.9/Pkg/src/API.jl:143
 [11] top-level scope
    @ REPL[4]:1

**Comment by ViralBShah** [comment]
Just tried: All tests pass for me on ubuntu.

(@v1.9) pkg> st
Status `~/.julia/environments/v1.9/Project.toml`
  [2b7a1792] Circuitscape v5.12.3

**Comment by ranjanan** [comment]
Okay I am able to reproduce this on v1.9 on my M2 Mac. Bizarre, looking into this.

**Comment by ViralBShah** [comment]
Dup of #364

**Comment by ViralBShah** [comment]
Dup of #364

**Comment by ViralBShah** [comment]
I'm now getting it to crash on my M2 as well.

**Comment by ranjanan** [comment]
This was breaking at the file writing stage, just like in #379. When I update my packages on Julia 1.9 and confirm that I have ArchGDAL 0.10.1, the tests pass.

**Comment by ViralBShah** [comment]
Should we update the dependency for ArchGDAL.jl to 0.10.1?

**Comment by ranjanan** [comment]
I am running tests with ArchGDAL 0.10.0 and Julia 1.8 and 1.9 and they all work fine. The folks in the thread seem to be on 5.12 and not 5.13. 

```Julia
import Pkg
Pkg.update()
```
should fix things for them.

**Comment by ranjanan** [comment]
My previous version that crashed had ArchGDAL 0.9.8

**Comment by ranjanan** [comment]
@harshadkarandikar could you try this out?

**Comment by ViralBShah** [comment]
On Julia 1.9, I am unable to get Circuitscape 5.12.3 pick up ArchGDAL 0.10.1. It insists on 0.9.4

**Comment by evetion** [comment]
This is a bug in ArchGDAL before v0.9.4 on aarch64 and Julia 1.9+. It was fixed in https://github.com/yeesian/ArchGDAL.jl/pull/352.

**Comment by ranjanan** [comment]
Thank you @evetion. This means we will bump our Julia version compat to 1.9.

**Comment by ViralBShah** [comment]
Folks, try Circuitscape 5.13 tomorrow.

**Comment by ranjanan** [comment]
https://github.com/JuliaRegistries/General/pull/89450
