### ISSUE TITLE
Issue writing map output

### ISSUE THREAD

**Issue by jsuraci** [Circuitscape/Circuitscape.jl#379]
Hi. I'm running Circuitscape v5.12.2 in "advanced" mode on Julia 1.8.5 and running into issues with writing the current map output to my local disk. With the .ini file copied below (in this case `write_cum_cur_map_only = false`), Circuitscape starts the job (and maybe even runs the calculations) but crashes Julia with a bus error (see screenshot).  If I change to `write_cum_cur_map_only = true`, the process runs to completion, but no map output is written... Any thoughts?

![Screen Shot 2023-03-14 at 10 36 55 AM](https://user-images.githubusercontent.com/48489957/225092282-a822ddbf-81cc-49be-87d1-d75825d4d057.png)

**FULL INI FILE CONTENT**
[Habitat raster or graph]
habitat_file = output/connectivity/resistance/tpres-cpres-ne4.tif
habitat_map_is_resistances = True

[Options for advanced mode]
ground_file_is_resistances = False
source_file = output/connectivity/src-grd/summer_exp_pres_010.tif
remove_src_or_gnd = keepall
ground_file = output/connectivity/src-grd/winter_exp_pres_010.tif
use_unit_currents = False
use_direct_grounds = False

[Calculation options]
low_memory_mode = False
solver = cholmod
print_timings = True

[Options for pairwise and one-to-all and all-to-one modes]
included_pairs_file = None
use_included_pairs = False
point_file = None

[Output options]
write_cum_cur_map_only = false
log_transform_maps = false
output_file = output/connectivity/circuitscape/test1
write_max_cur_maps = false
write_volt_maps = false
set_null_currents_to_nodata = false
set_null_voltages_to_nodata = false
compress_grids = false
write_cur_maps = true

[Short circuit regions (aka polygons)]
use_polygons = False
polygon_file = False

[Connection scheme for raster habitat data]
connect_four_neighbors_only = False
connect_using_avg_resistances = True

[Options for one-to-all and all-to-one modes]
use_variable_source_strengths = False
variable_source_file = None

[Version]
version = 5.0.0

[Mask file]
use_mask = False
mask_file = None

[Circuitscape mode]
data_type = raster
scenario = advanced

parallelize = True
max_parallel = 3

**Comment by ranjanan** [comment]
@jsuraci could you try `import Pkg; Pkg.update()` and run again? Make sure you're on Circuitscape 5.13
