### ISSUE TITLE
Circuitscape not running in container

### ISSUE THREAD

**Issue by ruegdeg** [Circuitscape/Circuitscape.jl#401]
Dear all, I tried to make the Julia Circuitscape to work within a Singularity container, installation goes good.
But while testing Iam getting this error about:::
SimpleWeightedGraphs:
LoadError: MethodError: no method matching connected_components(::SimpleWeightedGraphs.SimpleWeightedGraph{Int32,Float64})
Closest candidates are:
connected_components(!Matched::LightGraphs.AbstractGraph{T}) where T at /home/XX/.julia/packages/LightGraphs/IgJif/src/connectivity.jl:101
..
.
.
Any suggestions how to overcome this?

**Comment by ViralBShah** [comment]
Do you see this issue outside a Singularity container too?

**Comment by ranjanan** [comment]
@ruegdeg?
