### ISSUE TITLE
Is there a QGIS version of the Circuitscape Tool in ArcGIS?

### ISSUE THREAD

**Issue by cristianP04** [Circuitscape/Circuitscape.jl#402]
Hi Everyone, 

I am trying to prepare the Circuitscape input files with QGIS but I am encountering several problems with the format of the final asc files, meaning different headers and different extents of the final files. Specifically the resulting .asc file for the coordinates (which is going to be my focal node location file) has more rows and columns then other layers. All the layers have been clipped using the location shapefile as extent, so theoretically all the layers should have the same size.

I resume below the steps I follow to produce my files:

> To produce the “focal node location file” with the locations from a .csv: 
• I convert the location layer into a shapefile: right click to the file in the layer window > Export > Save as Feature > Select shapefile
• Then I rasterize the shapefile I just created: Raster > Conversion > Rasterize > select the shapefile as input > Field to use as burn in (it says optional but it seems to me to be actually mandatory, otherwise I get an essor) > Output raster units > Georeferenced units > set the two resolutions as 0.008 (1Km) > Output extent > use a raster wich has the correct extent > Save as file
•	To convert the tif file just created: Raster > Translate (convert format) > On “Output file” select “.asc”

> For other .tif file layers: Raster > Translate (convert format) > On “Output file” select “.asc”

I am using a MacBook Pro from 2015 and my QGIS version is the 3.22.8-Białowieża

I have never used it personally, but from what I understand there is a toll in ArcGIS that allows you to prepare all the files at once. Does anyone know if is there a similar tool in QGIS?

Thank you all in advance.

**Comment by ViralBShah** [comment]
I personally am not familiar with the rest of the QGIS tooling. In theory all this should work well, but someone familiar with QGIS and Circuitscape would need to iron out the issues.
