### ISSUE TITLE
Precompilation warning for a missing type

### ISSUE THREAD

**Issue by ollehwang** [Circuitscape/Circuitscape.jl#403]
I was installing the omniscape, and here is the warning. I wonder where did the error occur, circuitscape or omniscape

9 dependencies successfully precompiled in 11 seconds. 100 already precompiled.
  1 dependency had output during precompilation:
┌ Omniscape
│  WARNING: method definition for multiple_solver at C:\Users\28396\.julia\packages\Circuitscape\XcB67\src\raster\advanced.jl:275 declares type variable S but does not use it.
└

**Comment by ViralBShah** [comment]
It should be ok to ignore.

**Comment by ViralBShah** [comment]
Will leave this open to fix it in the future. Just needs to be deleted. PR appreciated.

**Comment by ViralBShah** [comment]
```
Precompiling project...
  80 dependencies successfully precompiled in 34 seconds. 6 already precompiled.
     Testing Running tests...
WARNING: method definition for multiple_solver at /Users/viral/.julia/packages/Circuitscape/XcB67/src/raster/advanced.jl:275 declares type variable S but does not use it.
WARNING: could not import Circuitscape.compute_mklpardiso into Main
pwd = /Users/viral/.julia/packages/Circuitscape/XcB67/test
```
