### ISSUE TITLE
different outputs from Circuitscape Python and Julia in advanced mode

### ISSUE THREAD

**Issue by cbogdanc** [Circuitscape/Circuitscape.jl#414]
Hello,

I have encountered an issue where I'm getting two different outputs when using the same input and configuration files in Circuitscape Python vs. Julia. The model setup has a rectangular shape resistance map, with source nodes around the perimeter (with discrete x,y coordinates in a text file) and ground nodes in a narrow band represented as raster cells (with the same node ID). In the advanced mode, the cumulative current output from the Python version has values in the 0-1 range, and in the Julia version has values in the  0-46 million range, and a different spatial distribution. 

Is this a known issue? Is there a way to obtain the same (or very similar) output from the two Circuitscape versions?

Thank you,
Bogdan

**Comment by cbogdanc** [comment]
As a comparison, the outputs in pairwise mode are exactly the same in the Python and Julia version. The test was done using the same resistance map and the same source nodes file (discrete points) as for the advanced mode, and a set of ground nodes represented as discrete points (along the narrow band described above).

Should I add the input files for the advanced mode simulations?

Thank you,
Bogdan

**Comment by ranjanan** [comment]
I didn't support `use_unit_currents` just yet. I've added support now through #421. I've verified that it produces the same output as the python package.
